// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_codex.proto

#ifndef PROTOBUF_cmd_2fcmd_5fcodex_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5fcodex_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class CodexDataFullNotify;
class CodexDataFullNotifyDefaultTypeInternal;
extern CodexDataFullNotifyDefaultTypeInternal _CodexDataFullNotify_default_instance_;
class CodexDataUpdateNotify;
class CodexDataUpdateNotifyDefaultTypeInternal;
extern CodexDataUpdateNotifyDefaultTypeInternal _CodexDataUpdateNotify_default_instance_;
class CodexTypeData;
class CodexTypeDataDefaultTypeInternal;
extern CodexTypeDataDefaultTypeInternal _CodexTypeData_default_instance_;
class CodexTypeData_WeaponMaxPromoteLevelMapEntry;
class CodexTypeData_WeaponMaxPromoteLevelMapEntryDefaultTypeInternal;
extern CodexTypeData_WeaponMaxPromoteLevelMapEntryDefaultTypeInternal _CodexTypeData_WeaponMaxPromoteLevelMapEntry_default_instance_;
class QueryCodexMonsterBeKilledNumReq;
class QueryCodexMonsterBeKilledNumReqDefaultTypeInternal;
extern QueryCodexMonsterBeKilledNumReqDefaultTypeInternal _QueryCodexMonsterBeKilledNumReq_default_instance_;
class QueryCodexMonsterBeKilledNumRsp;
class QueryCodexMonsterBeKilledNumRspDefaultTypeInternal;
extern QueryCodexMonsterBeKilledNumRspDefaultTypeInternal _QueryCodexMonsterBeKilledNumRsp_default_instance_;
class SetCodexPushtipsReadReq;
class SetCodexPushtipsReadReqDefaultTypeInternal;
extern SetCodexPushtipsReadReqDefaultTypeInternal _SetCodexPushtipsReadReq_default_instance_;
class SetCodexPushtipsReadRsp;
class SetCodexPushtipsReadRspDefaultTypeInternal;
extern SetCodexPushtipsReadRspDefaultTypeInternal _SetCodexPushtipsReadRsp_default_instance_;
class ViewCodexReq;
class ViewCodexReqDefaultTypeInternal;
extern ViewCodexReqDefaultTypeInternal _ViewCodexReq_default_instance_;
class ViewCodexRsp;
class ViewCodexRspDefaultTypeInternal;
extern ViewCodexRspDefaultTypeInternal _ViewCodexRsp_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5fcodex_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5fcodex_2eproto

enum CodexDataFullNotify_CmdId {
  CodexDataFullNotify_CmdId_NONE = 0,
  CodexDataFullNotify_CmdId_CMD_ID = 4205,
  CodexDataFullNotify_CmdId_ENET_CHANNEL_ID = 0,
  CodexDataFullNotify_CmdId_ENET_IS_RELIABLE = 1,
  CodexDataFullNotify_CmdId_CodexDataFullNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CodexDataFullNotify_CmdId_CodexDataFullNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CodexDataFullNotify_CmdId_IsValid(int value);
const CodexDataFullNotify_CmdId CodexDataFullNotify_CmdId_CmdId_MIN = CodexDataFullNotify_CmdId_NONE;
const CodexDataFullNotify_CmdId CodexDataFullNotify_CmdId_CmdId_MAX = CodexDataFullNotify_CmdId_CMD_ID;
const int CodexDataFullNotify_CmdId_CmdId_ARRAYSIZE = CodexDataFullNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* CodexDataFullNotify_CmdId_descriptor();
inline const ::std::string& CodexDataFullNotify_CmdId_Name(CodexDataFullNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    CodexDataFullNotify_CmdId_descriptor(), value);
}
inline bool CodexDataFullNotify_CmdId_Parse(
    const ::std::string& name, CodexDataFullNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CodexDataFullNotify_CmdId>(
    CodexDataFullNotify_CmdId_descriptor(), name, value);
}
enum CodexDataUpdateNotify_CmdId {
  CodexDataUpdateNotify_CmdId_NONE = 0,
  CodexDataUpdateNotify_CmdId_CMD_ID = 4207,
  CodexDataUpdateNotify_CmdId_ENET_CHANNEL_ID = 0,
  CodexDataUpdateNotify_CmdId_ENET_IS_RELIABLE = 1,
  CodexDataUpdateNotify_CmdId_CodexDataUpdateNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CodexDataUpdateNotify_CmdId_CodexDataUpdateNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CodexDataUpdateNotify_CmdId_IsValid(int value);
const CodexDataUpdateNotify_CmdId CodexDataUpdateNotify_CmdId_CmdId_MIN = CodexDataUpdateNotify_CmdId_NONE;
const CodexDataUpdateNotify_CmdId CodexDataUpdateNotify_CmdId_CmdId_MAX = CodexDataUpdateNotify_CmdId_CMD_ID;
const int CodexDataUpdateNotify_CmdId_CmdId_ARRAYSIZE = CodexDataUpdateNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* CodexDataUpdateNotify_CmdId_descriptor();
inline const ::std::string& CodexDataUpdateNotify_CmdId_Name(CodexDataUpdateNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    CodexDataUpdateNotify_CmdId_descriptor(), value);
}
inline bool CodexDataUpdateNotify_CmdId_Parse(
    const ::std::string& name, CodexDataUpdateNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CodexDataUpdateNotify_CmdId>(
    CodexDataUpdateNotify_CmdId_descriptor(), name, value);
}
enum QueryCodexMonsterBeKilledNumReq_CmdId {
  QueryCodexMonsterBeKilledNumReq_CmdId_NONE = 0,
  QueryCodexMonsterBeKilledNumReq_CmdId_CMD_ID = 4203,
  QueryCodexMonsterBeKilledNumReq_CmdId_ENET_CHANNEL_ID = 0,
  QueryCodexMonsterBeKilledNumReq_CmdId_ENET_IS_RELIABLE = 1,
  QueryCodexMonsterBeKilledNumReq_CmdId_IS_ALLOW_CLIENT = 1,
  QueryCodexMonsterBeKilledNumReq_CmdId_QueryCodexMonsterBeKilledNumReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  QueryCodexMonsterBeKilledNumReq_CmdId_QueryCodexMonsterBeKilledNumReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool QueryCodexMonsterBeKilledNumReq_CmdId_IsValid(int value);
const QueryCodexMonsterBeKilledNumReq_CmdId QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_MIN = QueryCodexMonsterBeKilledNumReq_CmdId_NONE;
const QueryCodexMonsterBeKilledNumReq_CmdId QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_MAX = QueryCodexMonsterBeKilledNumReq_CmdId_CMD_ID;
const int QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_ARRAYSIZE = QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryCodexMonsterBeKilledNumReq_CmdId_descriptor();
inline const ::std::string& QueryCodexMonsterBeKilledNumReq_CmdId_Name(QueryCodexMonsterBeKilledNumReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryCodexMonsterBeKilledNumReq_CmdId_descriptor(), value);
}
inline bool QueryCodexMonsterBeKilledNumReq_CmdId_Parse(
    const ::std::string& name, QueryCodexMonsterBeKilledNumReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryCodexMonsterBeKilledNumReq_CmdId>(
    QueryCodexMonsterBeKilledNumReq_CmdId_descriptor(), name, value);
}
enum QueryCodexMonsterBeKilledNumRsp_CmdId {
  QueryCodexMonsterBeKilledNumRsp_CmdId_NONE = 0,
  QueryCodexMonsterBeKilledNumRsp_CmdId_CMD_ID = 4209,
  QueryCodexMonsterBeKilledNumRsp_CmdId_ENET_CHANNEL_ID = 0,
  QueryCodexMonsterBeKilledNumRsp_CmdId_ENET_IS_RELIABLE = 1,
  QueryCodexMonsterBeKilledNumRsp_CmdId_QueryCodexMonsterBeKilledNumRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  QueryCodexMonsterBeKilledNumRsp_CmdId_QueryCodexMonsterBeKilledNumRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool QueryCodexMonsterBeKilledNumRsp_CmdId_IsValid(int value);
const QueryCodexMonsterBeKilledNumRsp_CmdId QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_MIN = QueryCodexMonsterBeKilledNumRsp_CmdId_NONE;
const QueryCodexMonsterBeKilledNumRsp_CmdId QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_MAX = QueryCodexMonsterBeKilledNumRsp_CmdId_CMD_ID;
const int QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_ARRAYSIZE = QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryCodexMonsterBeKilledNumRsp_CmdId_descriptor();
inline const ::std::string& QueryCodexMonsterBeKilledNumRsp_CmdId_Name(QueryCodexMonsterBeKilledNumRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryCodexMonsterBeKilledNumRsp_CmdId_descriptor(), value);
}
inline bool QueryCodexMonsterBeKilledNumRsp_CmdId_Parse(
    const ::std::string& name, QueryCodexMonsterBeKilledNumRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryCodexMonsterBeKilledNumRsp_CmdId>(
    QueryCodexMonsterBeKilledNumRsp_CmdId_descriptor(), name, value);
}
enum ViewCodexReq_CmdId {
  ViewCodexReq_CmdId_NONE = 0,
  ViewCodexReq_CmdId_CMD_ID = 4202,
  ViewCodexReq_CmdId_ENET_CHANNEL_ID = 0,
  ViewCodexReq_CmdId_ENET_IS_RELIABLE = 1,
  ViewCodexReq_CmdId_IS_ALLOW_CLIENT = 1,
  ViewCodexReq_CmdId_ViewCodexReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ViewCodexReq_CmdId_ViewCodexReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ViewCodexReq_CmdId_IsValid(int value);
const ViewCodexReq_CmdId ViewCodexReq_CmdId_CmdId_MIN = ViewCodexReq_CmdId_NONE;
const ViewCodexReq_CmdId ViewCodexReq_CmdId_CmdId_MAX = ViewCodexReq_CmdId_CMD_ID;
const int ViewCodexReq_CmdId_CmdId_ARRAYSIZE = ViewCodexReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* ViewCodexReq_CmdId_descriptor();
inline const ::std::string& ViewCodexReq_CmdId_Name(ViewCodexReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    ViewCodexReq_CmdId_descriptor(), value);
}
inline bool ViewCodexReq_CmdId_Parse(
    const ::std::string& name, ViewCodexReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ViewCodexReq_CmdId>(
    ViewCodexReq_CmdId_descriptor(), name, value);
}
enum ViewCodexRsp_CmdId {
  ViewCodexRsp_CmdId_NONE = 0,
  ViewCodexRsp_CmdId_CMD_ID = 4201,
  ViewCodexRsp_CmdId_ENET_CHANNEL_ID = 0,
  ViewCodexRsp_CmdId_ENET_IS_RELIABLE = 1,
  ViewCodexRsp_CmdId_ViewCodexRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ViewCodexRsp_CmdId_ViewCodexRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ViewCodexRsp_CmdId_IsValid(int value);
const ViewCodexRsp_CmdId ViewCodexRsp_CmdId_CmdId_MIN = ViewCodexRsp_CmdId_NONE;
const ViewCodexRsp_CmdId ViewCodexRsp_CmdId_CmdId_MAX = ViewCodexRsp_CmdId_CMD_ID;
const int ViewCodexRsp_CmdId_CmdId_ARRAYSIZE = ViewCodexRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* ViewCodexRsp_CmdId_descriptor();
inline const ::std::string& ViewCodexRsp_CmdId_Name(ViewCodexRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    ViewCodexRsp_CmdId_descriptor(), value);
}
inline bool ViewCodexRsp_CmdId_Parse(
    const ::std::string& name, ViewCodexRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ViewCodexRsp_CmdId>(
    ViewCodexRsp_CmdId_descriptor(), name, value);
}
enum SetCodexPushtipsReadReq_CmdId {
  SetCodexPushtipsReadReq_CmdId_NONE = 0,
  SetCodexPushtipsReadReq_CmdId_CMD_ID = 4208,
  SetCodexPushtipsReadReq_CmdId_ENET_CHANNEL_ID = 0,
  SetCodexPushtipsReadReq_CmdId_ENET_IS_RELIABLE = 1,
  SetCodexPushtipsReadReq_CmdId_IS_ALLOW_CLIENT = 1,
  SetCodexPushtipsReadReq_CmdId_SetCodexPushtipsReadReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SetCodexPushtipsReadReq_CmdId_SetCodexPushtipsReadReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SetCodexPushtipsReadReq_CmdId_IsValid(int value);
const SetCodexPushtipsReadReq_CmdId SetCodexPushtipsReadReq_CmdId_CmdId_MIN = SetCodexPushtipsReadReq_CmdId_NONE;
const SetCodexPushtipsReadReq_CmdId SetCodexPushtipsReadReq_CmdId_CmdId_MAX = SetCodexPushtipsReadReq_CmdId_CMD_ID;
const int SetCodexPushtipsReadReq_CmdId_CmdId_ARRAYSIZE = SetCodexPushtipsReadReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* SetCodexPushtipsReadReq_CmdId_descriptor();
inline const ::std::string& SetCodexPushtipsReadReq_CmdId_Name(SetCodexPushtipsReadReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    SetCodexPushtipsReadReq_CmdId_descriptor(), value);
}
inline bool SetCodexPushtipsReadReq_CmdId_Parse(
    const ::std::string& name, SetCodexPushtipsReadReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SetCodexPushtipsReadReq_CmdId>(
    SetCodexPushtipsReadReq_CmdId_descriptor(), name, value);
}
enum SetCodexPushtipsReadRsp_CmdId {
  SetCodexPushtipsReadRsp_CmdId_NONE = 0,
  SetCodexPushtipsReadRsp_CmdId_CMD_ID = 4206,
  SetCodexPushtipsReadRsp_CmdId_ENET_CHANNEL_ID = 0,
  SetCodexPushtipsReadRsp_CmdId_ENET_IS_RELIABLE = 1,
  SetCodexPushtipsReadRsp_CmdId_SetCodexPushtipsReadRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SetCodexPushtipsReadRsp_CmdId_SetCodexPushtipsReadRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SetCodexPushtipsReadRsp_CmdId_IsValid(int value);
const SetCodexPushtipsReadRsp_CmdId SetCodexPushtipsReadRsp_CmdId_CmdId_MIN = SetCodexPushtipsReadRsp_CmdId_NONE;
const SetCodexPushtipsReadRsp_CmdId SetCodexPushtipsReadRsp_CmdId_CmdId_MAX = SetCodexPushtipsReadRsp_CmdId_CMD_ID;
const int SetCodexPushtipsReadRsp_CmdId_CmdId_ARRAYSIZE = SetCodexPushtipsReadRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* SetCodexPushtipsReadRsp_CmdId_descriptor();
inline const ::std::string& SetCodexPushtipsReadRsp_CmdId_Name(SetCodexPushtipsReadRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    SetCodexPushtipsReadRsp_CmdId_descriptor(), value);
}
inline bool SetCodexPushtipsReadRsp_CmdId_Parse(
    const ::std::string& name, SetCodexPushtipsReadRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SetCodexPushtipsReadRsp_CmdId>(
    SetCodexPushtipsReadRsp_CmdId_descriptor(), name, value);
}
// ===================================================================


// -------------------------------------------------------------------

class CodexTypeData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CodexTypeData) */ {
 public:
  CodexTypeData();
  virtual ~CodexTypeData();

  CodexTypeData(const CodexTypeData& from);

  inline CodexTypeData& operator=(const CodexTypeData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodexTypeData(CodexTypeData&& from) noexcept
    : CodexTypeData() {
    *this = ::std::move(from);
  }

  inline CodexTypeData& operator=(CodexTypeData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodexTypeData& default_instance();

  static inline const CodexTypeData* internal_default_instance() {
    return reinterpret_cast<const CodexTypeData*>(
               &_CodexTypeData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(CodexTypeData* other);
  friend void swap(CodexTypeData& a, CodexTypeData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodexTypeData* New() const PROTOBUF_FINAL { return New(NULL); }

  CodexTypeData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CodexTypeData& from);
  void MergeFrom(const CodexTypeData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CodexTypeData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, uint32> weapon_max_promote_level_map = 4;
  int weapon_max_promote_level_map_size() const;
  void clear_weapon_max_promote_level_map();
  static const int kWeaponMaxPromoteLevelMapFieldNumber = 4;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
      weapon_max_promote_level_map() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
      mutable_weapon_max_promote_level_map();

  // repeated bool have_viewed_list = 5;
  int have_viewed_list_size() const;
  void clear_have_viewed_list();
  static const int kHaveViewedListFieldNumber = 5;
  bool have_viewed_list(int index) const;
  void set_have_viewed_list(int index, bool value);
  void add_have_viewed_list(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      have_viewed_list() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_have_viewed_list();

  // repeated uint32 codex_id_list = 14;
  int codex_id_list_size() const;
  void clear_codex_id_list();
  static const int kCodexIdListFieldNumber = 14;
  ::google::protobuf::uint32 codex_id_list(int index) const;
  void set_codex_id_list(int index, ::google::protobuf::uint32 value);
  void add_codex_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      codex_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_codex_id_list();

  // .proto.CodexType type = 13;
  void clear_type();
  static const int kTypeFieldNumber = 13;
  ::proto::CodexType type() const;
  void set_type(::proto::CodexType value);

  // @@protoc_insertion_point(class_scope:proto.CodexTypeData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class CodexTypeData_WeaponMaxPromoteLevelMapEntry : public ::google::protobuf::internal::MapEntry<CodexTypeData_WeaponMaxPromoteLevelMapEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<CodexTypeData_WeaponMaxPromoteLevelMapEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > SuperType;
    CodexTypeData_WeaponMaxPromoteLevelMapEntry();
    CodexTypeData_WeaponMaxPromoteLevelMapEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const CodexTypeData_WeaponMaxPromoteLevelMapEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_CodexTypeData_WeaponMaxPromoteLevelMapEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      CodexTypeData_WeaponMaxPromoteLevelMapEntry,
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > weapon_max_promote_level_map_;
  private:
  ::google::protobuf::RepeatedField< bool > have_viewed_list_;
  mutable int _have_viewed_list_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > codex_id_list_;
  mutable int _codex_id_list_cached_byte_size_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CodexDataFullNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CodexDataFullNotify) */ {
 public:
  CodexDataFullNotify();
  virtual ~CodexDataFullNotify();

  CodexDataFullNotify(const CodexDataFullNotify& from);

  inline CodexDataFullNotify& operator=(const CodexDataFullNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodexDataFullNotify(CodexDataFullNotify&& from) noexcept
    : CodexDataFullNotify() {
    *this = ::std::move(from);
  }

  inline CodexDataFullNotify& operator=(CodexDataFullNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodexDataFullNotify& default_instance();

  static inline const CodexDataFullNotify* internal_default_instance() {
    return reinterpret_cast<const CodexDataFullNotify*>(
               &_CodexDataFullNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(CodexDataFullNotify* other);
  friend void swap(CodexDataFullNotify& a, CodexDataFullNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodexDataFullNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  CodexDataFullNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CodexDataFullNotify& from);
  void MergeFrom(const CodexDataFullNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CodexDataFullNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CodexDataFullNotify_CmdId CmdId;
  static const CmdId NONE =
    CodexDataFullNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    CodexDataFullNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    CodexDataFullNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    CodexDataFullNotify_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return CodexDataFullNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    CodexDataFullNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    CodexDataFullNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    CodexDataFullNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return CodexDataFullNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return CodexDataFullNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return CodexDataFullNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated uint32 recent_viewed_pushtips_list = 2;
  int recent_viewed_pushtips_list_size() const;
  void clear_recent_viewed_pushtips_list();
  static const int kRecentViewedPushtipsListFieldNumber = 2;
  ::google::protobuf::uint32 recent_viewed_pushtips_list(int index) const;
  void set_recent_viewed_pushtips_list(int index, ::google::protobuf::uint32 value);
  void add_recent_viewed_pushtips_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      recent_viewed_pushtips_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_recent_viewed_pushtips_list();

  // repeated .proto.CodexTypeData type_data_list = 6;
  int type_data_list_size() const;
  void clear_type_data_list();
  static const int kTypeDataListFieldNumber = 6;
  const ::proto::CodexTypeData& type_data_list(int index) const;
  ::proto::CodexTypeData* mutable_type_data_list(int index);
  ::proto::CodexTypeData* add_type_data_list();
  ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >*
      mutable_type_data_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >&
      type_data_list() const;

  // uint32 last_read_pushtips_type_id = 3;
  void clear_last_read_pushtips_type_id();
  static const int kLastReadPushtipsTypeIdFieldNumber = 3;
  ::google::protobuf::uint32 last_read_pushtips_type_id() const;
  void set_last_read_pushtips_type_id(::google::protobuf::uint32 value);

  // uint32 last_read_pushtips_codex_id = 4;
  void clear_last_read_pushtips_codex_id();
  static const int kLastReadPushtipsCodexIdFieldNumber = 4;
  ::google::protobuf::uint32 last_read_pushtips_codex_id() const;
  void set_last_read_pushtips_codex_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.CodexDataFullNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > recent_viewed_pushtips_list_;
  mutable int _recent_viewed_pushtips_list_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData > type_data_list_;
  ::google::protobuf::uint32 last_read_pushtips_type_id_;
  ::google::protobuf::uint32 last_read_pushtips_codex_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CodexDataUpdateNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CodexDataUpdateNotify) */ {
 public:
  CodexDataUpdateNotify();
  virtual ~CodexDataUpdateNotify();

  CodexDataUpdateNotify(const CodexDataUpdateNotify& from);

  inline CodexDataUpdateNotify& operator=(const CodexDataUpdateNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodexDataUpdateNotify(CodexDataUpdateNotify&& from) noexcept
    : CodexDataUpdateNotify() {
    *this = ::std::move(from);
  }

  inline CodexDataUpdateNotify& operator=(CodexDataUpdateNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodexDataUpdateNotify& default_instance();

  static inline const CodexDataUpdateNotify* internal_default_instance() {
    return reinterpret_cast<const CodexDataUpdateNotify*>(
               &_CodexDataUpdateNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(CodexDataUpdateNotify* other);
  friend void swap(CodexDataUpdateNotify& a, CodexDataUpdateNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodexDataUpdateNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  CodexDataUpdateNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CodexDataUpdateNotify& from);
  void MergeFrom(const CodexDataUpdateNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CodexDataUpdateNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CodexDataUpdateNotify_CmdId CmdId;
  static const CmdId NONE =
    CodexDataUpdateNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    CodexDataUpdateNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    CodexDataUpdateNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    CodexDataUpdateNotify_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return CodexDataUpdateNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    CodexDataUpdateNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    CodexDataUpdateNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    CodexDataUpdateNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return CodexDataUpdateNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return CodexDataUpdateNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return CodexDataUpdateNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 weapon_max_promote_level = 15;
  void clear_weapon_max_promote_level();
  static const int kWeaponMaxPromoteLevelFieldNumber = 15;
  ::google::protobuf::uint32 weapon_max_promote_level() const;
  void set_weapon_max_promote_level(::google::protobuf::uint32 value);

  // uint32 id = 8;
  void clear_id();
  static const int kIdFieldNumber = 8;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // .proto.CodexType type = 11;
  void clear_type();
  static const int kTypeFieldNumber = 11;
  ::proto::CodexType type() const;
  void set_type(::proto::CodexType value);

  // @@protoc_insertion_point(class_scope:proto.CodexDataUpdateNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 weapon_max_promote_level_;
  ::google::protobuf::uint32 id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class QueryCodexMonsterBeKilledNumReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.QueryCodexMonsterBeKilledNumReq) */ {
 public:
  QueryCodexMonsterBeKilledNumReq();
  virtual ~QueryCodexMonsterBeKilledNumReq();

  QueryCodexMonsterBeKilledNumReq(const QueryCodexMonsterBeKilledNumReq& from);

  inline QueryCodexMonsterBeKilledNumReq& operator=(const QueryCodexMonsterBeKilledNumReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  QueryCodexMonsterBeKilledNumReq(QueryCodexMonsterBeKilledNumReq&& from) noexcept
    : QueryCodexMonsterBeKilledNumReq() {
    *this = ::std::move(from);
  }

  inline QueryCodexMonsterBeKilledNumReq& operator=(QueryCodexMonsterBeKilledNumReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryCodexMonsterBeKilledNumReq& default_instance();

  static inline const QueryCodexMonsterBeKilledNumReq* internal_default_instance() {
    return reinterpret_cast<const QueryCodexMonsterBeKilledNumReq*>(
               &_QueryCodexMonsterBeKilledNumReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(QueryCodexMonsterBeKilledNumReq* other);
  friend void swap(QueryCodexMonsterBeKilledNumReq& a, QueryCodexMonsterBeKilledNumReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline QueryCodexMonsterBeKilledNumReq* New() const PROTOBUF_FINAL { return New(NULL); }

  QueryCodexMonsterBeKilledNumReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const QueryCodexMonsterBeKilledNumReq& from);
  void MergeFrom(const QueryCodexMonsterBeKilledNumReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(QueryCodexMonsterBeKilledNumReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef QueryCodexMonsterBeKilledNumReq_CmdId CmdId;
  static const CmdId NONE =
    QueryCodexMonsterBeKilledNumReq_CmdId_NONE;
  static const CmdId CMD_ID =
    QueryCodexMonsterBeKilledNumReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    QueryCodexMonsterBeKilledNumReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    QueryCodexMonsterBeKilledNumReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    QueryCodexMonsterBeKilledNumReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return QueryCodexMonsterBeKilledNumReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    QueryCodexMonsterBeKilledNumReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return QueryCodexMonsterBeKilledNumReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return QueryCodexMonsterBeKilledNumReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return QueryCodexMonsterBeKilledNumReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated uint32 codex_id_list = 14;
  int codex_id_list_size() const;
  void clear_codex_id_list();
  static const int kCodexIdListFieldNumber = 14;
  ::google::protobuf::uint32 codex_id_list(int index) const;
  void set_codex_id_list(int index, ::google::protobuf::uint32 value);
  void add_codex_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      codex_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_codex_id_list();

  // @@protoc_insertion_point(class_scope:proto.QueryCodexMonsterBeKilledNumReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > codex_id_list_;
  mutable int _codex_id_list_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class QueryCodexMonsterBeKilledNumRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.QueryCodexMonsterBeKilledNumRsp) */ {
 public:
  QueryCodexMonsterBeKilledNumRsp();
  virtual ~QueryCodexMonsterBeKilledNumRsp();

  QueryCodexMonsterBeKilledNumRsp(const QueryCodexMonsterBeKilledNumRsp& from);

  inline QueryCodexMonsterBeKilledNumRsp& operator=(const QueryCodexMonsterBeKilledNumRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  QueryCodexMonsterBeKilledNumRsp(QueryCodexMonsterBeKilledNumRsp&& from) noexcept
    : QueryCodexMonsterBeKilledNumRsp() {
    *this = ::std::move(from);
  }

  inline QueryCodexMonsterBeKilledNumRsp& operator=(QueryCodexMonsterBeKilledNumRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryCodexMonsterBeKilledNumRsp& default_instance();

  static inline const QueryCodexMonsterBeKilledNumRsp* internal_default_instance() {
    return reinterpret_cast<const QueryCodexMonsterBeKilledNumRsp*>(
               &_QueryCodexMonsterBeKilledNumRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(QueryCodexMonsterBeKilledNumRsp* other);
  friend void swap(QueryCodexMonsterBeKilledNumRsp& a, QueryCodexMonsterBeKilledNumRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline QueryCodexMonsterBeKilledNumRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  QueryCodexMonsterBeKilledNumRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const QueryCodexMonsterBeKilledNumRsp& from);
  void MergeFrom(const QueryCodexMonsterBeKilledNumRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(QueryCodexMonsterBeKilledNumRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef QueryCodexMonsterBeKilledNumRsp_CmdId CmdId;
  static const CmdId NONE =
    QueryCodexMonsterBeKilledNumRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    QueryCodexMonsterBeKilledNumRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    QueryCodexMonsterBeKilledNumRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    QueryCodexMonsterBeKilledNumRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return QueryCodexMonsterBeKilledNumRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    QueryCodexMonsterBeKilledNumRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return QueryCodexMonsterBeKilledNumRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return QueryCodexMonsterBeKilledNumRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return QueryCodexMonsterBeKilledNumRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated uint32 codex_id_list = 4;
  int codex_id_list_size() const;
  void clear_codex_id_list();
  static const int kCodexIdListFieldNumber = 4;
  ::google::protobuf::uint32 codex_id_list(int index) const;
  void set_codex_id_list(int index, ::google::protobuf::uint32 value);
  void add_codex_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      codex_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_codex_id_list();

  // repeated uint32 be_captured_num_list = 6;
  int be_captured_num_list_size() const;
  void clear_be_captured_num_list();
  static const int kBeCapturedNumListFieldNumber = 6;
  ::google::protobuf::uint32 be_captured_num_list(int index) const;
  void set_be_captured_num_list(int index, ::google::protobuf::uint32 value);
  void add_be_captured_num_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      be_captured_num_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_be_captured_num_list();

  // repeated uint32 be_killed_num_list = 12;
  int be_killed_num_list_size() const;
  void clear_be_killed_num_list();
  static const int kBeKilledNumListFieldNumber = 12;
  ::google::protobuf::uint32 be_killed_num_list(int index) const;
  void set_be_killed_num_list(int index, ::google::protobuf::uint32 value);
  void add_be_killed_num_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      be_killed_num_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_be_killed_num_list();

  // int32 retcode = 5;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 5;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.QueryCodexMonsterBeKilledNumRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > codex_id_list_;
  mutable int _codex_id_list_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > be_captured_num_list_;
  mutable int _be_captured_num_list_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > be_killed_num_list_;
  mutable int _be_killed_num_list_cached_byte_size_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ViewCodexReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.ViewCodexReq) */ {
 public:
  ViewCodexReq();
  virtual ~ViewCodexReq();

  ViewCodexReq(const ViewCodexReq& from);

  inline ViewCodexReq& operator=(const ViewCodexReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ViewCodexReq(ViewCodexReq&& from) noexcept
    : ViewCodexReq() {
    *this = ::std::move(from);
  }

  inline ViewCodexReq& operator=(ViewCodexReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ViewCodexReq& default_instance();

  static inline const ViewCodexReq* internal_default_instance() {
    return reinterpret_cast<const ViewCodexReq*>(
               &_ViewCodexReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ViewCodexReq* other);
  friend void swap(ViewCodexReq& a, ViewCodexReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ViewCodexReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ViewCodexReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ViewCodexReq& from);
  void MergeFrom(const ViewCodexReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ViewCodexReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ViewCodexReq_CmdId CmdId;
  static const CmdId NONE =
    ViewCodexReq_CmdId_NONE;
  static const CmdId CMD_ID =
    ViewCodexReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    ViewCodexReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    ViewCodexReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    ViewCodexReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return ViewCodexReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    ViewCodexReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    ViewCodexReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    ViewCodexReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return ViewCodexReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return ViewCodexReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return ViewCodexReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.CodexTypeData type_data_list = 10;
  int type_data_list_size() const;
  void clear_type_data_list();
  static const int kTypeDataListFieldNumber = 10;
  const ::proto::CodexTypeData& type_data_list(int index) const;
  ::proto::CodexTypeData* mutable_type_data_list(int index);
  ::proto::CodexTypeData* add_type_data_list();
  ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >*
      mutable_type_data_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >&
      type_data_list() const;

  // @@protoc_insertion_point(class_scope:proto.ViewCodexReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData > type_data_list_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ViewCodexRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.ViewCodexRsp) */ {
 public:
  ViewCodexRsp();
  virtual ~ViewCodexRsp();

  ViewCodexRsp(const ViewCodexRsp& from);

  inline ViewCodexRsp& operator=(const ViewCodexRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ViewCodexRsp(ViewCodexRsp&& from) noexcept
    : ViewCodexRsp() {
    *this = ::std::move(from);
  }

  inline ViewCodexRsp& operator=(ViewCodexRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ViewCodexRsp& default_instance();

  static inline const ViewCodexRsp* internal_default_instance() {
    return reinterpret_cast<const ViewCodexRsp*>(
               &_ViewCodexRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ViewCodexRsp* other);
  friend void swap(ViewCodexRsp& a, ViewCodexRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ViewCodexRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ViewCodexRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ViewCodexRsp& from);
  void MergeFrom(const ViewCodexRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ViewCodexRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ViewCodexRsp_CmdId CmdId;
  static const CmdId NONE =
    ViewCodexRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    ViewCodexRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    ViewCodexRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    ViewCodexRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return ViewCodexRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    ViewCodexRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    ViewCodexRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    ViewCodexRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return ViewCodexRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return ViewCodexRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return ViewCodexRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated uint32 recent_viewed_pushtips_list = 3;
  int recent_viewed_pushtips_list_size() const;
  void clear_recent_viewed_pushtips_list();
  static const int kRecentViewedPushtipsListFieldNumber = 3;
  ::google::protobuf::uint32 recent_viewed_pushtips_list(int index) const;
  void set_recent_viewed_pushtips_list(int index, ::google::protobuf::uint32 value);
  void add_recent_viewed_pushtips_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      recent_viewed_pushtips_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_recent_viewed_pushtips_list();

  // repeated .proto.CodexTypeData type_data_list = 9;
  int type_data_list_size() const;
  void clear_type_data_list();
  static const int kTypeDataListFieldNumber = 9;
  const ::proto::CodexTypeData& type_data_list(int index) const;
  ::proto::CodexTypeData* mutable_type_data_list(int index);
  ::proto::CodexTypeData* add_type_data_list();
  ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >*
      mutable_type_data_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >&
      type_data_list() const;

  // repeated uint32 push_tips_reward_list = 10;
  int push_tips_reward_list_size() const;
  void clear_push_tips_reward_list();
  static const int kPushTipsRewardListFieldNumber = 10;
  ::google::protobuf::uint32 push_tips_reward_list(int index) const;
  void set_push_tips_reward_list(int index, ::google::protobuf::uint32 value);
  void add_push_tips_reward_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      push_tips_reward_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_push_tips_reward_list();

  // repeated uint32 push_tips_read_list = 15;
  int push_tips_read_list_size() const;
  void clear_push_tips_read_list();
  static const int kPushTipsReadListFieldNumber = 15;
  ::google::protobuf::uint32 push_tips_read_list(int index) const;
  void set_push_tips_read_list(int index, ::google::protobuf::uint32 value);
  void add_push_tips_read_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      push_tips_read_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_push_tips_read_list();

  // int32 retcode = 12;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 12;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.ViewCodexRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > recent_viewed_pushtips_list_;
  mutable int _recent_viewed_pushtips_list_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData > type_data_list_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > push_tips_reward_list_;
  mutable int _push_tips_reward_list_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > push_tips_read_list_;
  mutable int _push_tips_read_list_cached_byte_size_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetCodexPushtipsReadReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.SetCodexPushtipsReadReq) */ {
 public:
  SetCodexPushtipsReadReq();
  virtual ~SetCodexPushtipsReadReq();

  SetCodexPushtipsReadReq(const SetCodexPushtipsReadReq& from);

  inline SetCodexPushtipsReadReq& operator=(const SetCodexPushtipsReadReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetCodexPushtipsReadReq(SetCodexPushtipsReadReq&& from) noexcept
    : SetCodexPushtipsReadReq() {
    *this = ::std::move(from);
  }

  inline SetCodexPushtipsReadReq& operator=(SetCodexPushtipsReadReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SetCodexPushtipsReadReq& default_instance();

  static inline const SetCodexPushtipsReadReq* internal_default_instance() {
    return reinterpret_cast<const SetCodexPushtipsReadReq*>(
               &_SetCodexPushtipsReadReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(SetCodexPushtipsReadReq* other);
  friend void swap(SetCodexPushtipsReadReq& a, SetCodexPushtipsReadReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetCodexPushtipsReadReq* New() const PROTOBUF_FINAL { return New(NULL); }

  SetCodexPushtipsReadReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SetCodexPushtipsReadReq& from);
  void MergeFrom(const SetCodexPushtipsReadReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetCodexPushtipsReadReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SetCodexPushtipsReadReq_CmdId CmdId;
  static const CmdId NONE =
    SetCodexPushtipsReadReq_CmdId_NONE;
  static const CmdId CMD_ID =
    SetCodexPushtipsReadReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    SetCodexPushtipsReadReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    SetCodexPushtipsReadReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    SetCodexPushtipsReadReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return SetCodexPushtipsReadReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    SetCodexPushtipsReadReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    SetCodexPushtipsReadReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    SetCodexPushtipsReadReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return SetCodexPushtipsReadReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return SetCodexPushtipsReadReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return SetCodexPushtipsReadReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 type_id = 2;
  void clear_type_id();
  static const int kTypeIdFieldNumber = 2;
  ::google::protobuf::uint32 type_id() const;
  void set_type_id(::google::protobuf::uint32 value);

  // uint32 codex_id = 14;
  void clear_codex_id();
  static const int kCodexIdFieldNumber = 14;
  ::google::protobuf::uint32 codex_id() const;
  void set_codex_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.SetCodexPushtipsReadReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 type_id_;
  ::google::protobuf::uint32 codex_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetCodexPushtipsReadRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.SetCodexPushtipsReadRsp) */ {
 public:
  SetCodexPushtipsReadRsp();
  virtual ~SetCodexPushtipsReadRsp();

  SetCodexPushtipsReadRsp(const SetCodexPushtipsReadRsp& from);

  inline SetCodexPushtipsReadRsp& operator=(const SetCodexPushtipsReadRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetCodexPushtipsReadRsp(SetCodexPushtipsReadRsp&& from) noexcept
    : SetCodexPushtipsReadRsp() {
    *this = ::std::move(from);
  }

  inline SetCodexPushtipsReadRsp& operator=(SetCodexPushtipsReadRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SetCodexPushtipsReadRsp& default_instance();

  static inline const SetCodexPushtipsReadRsp* internal_default_instance() {
    return reinterpret_cast<const SetCodexPushtipsReadRsp*>(
               &_SetCodexPushtipsReadRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(SetCodexPushtipsReadRsp* other);
  friend void swap(SetCodexPushtipsReadRsp& a, SetCodexPushtipsReadRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetCodexPushtipsReadRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  SetCodexPushtipsReadRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SetCodexPushtipsReadRsp& from);
  void MergeFrom(const SetCodexPushtipsReadRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetCodexPushtipsReadRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SetCodexPushtipsReadRsp_CmdId CmdId;
  static const CmdId NONE =
    SetCodexPushtipsReadRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    SetCodexPushtipsReadRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    SetCodexPushtipsReadRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    SetCodexPushtipsReadRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return SetCodexPushtipsReadRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    SetCodexPushtipsReadRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    SetCodexPushtipsReadRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    SetCodexPushtipsReadRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return SetCodexPushtipsReadRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return SetCodexPushtipsReadRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return SetCodexPushtipsReadRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 codex_id = 14;
  void clear_codex_id();
  static const int kCodexIdFieldNumber = 14;
  ::google::protobuf::uint32 codex_id() const;
  void set_codex_id(::google::protobuf::uint32 value);

  // uint32 type_id = 5;
  void clear_type_id();
  static const int kTypeIdFieldNumber = 5;
  ::google::protobuf::uint32 type_id() const;
  void set_type_id(::google::protobuf::uint32 value);

  // int32 retcode = 10;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 10;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.SetCodexPushtipsReadRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 codex_id_;
  ::google::protobuf::uint32 type_id_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fcodex_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CodexTypeData

// repeated uint32 codex_id_list = 14;
inline int CodexTypeData::codex_id_list_size() const {
  return codex_id_list_.size();
}
inline void CodexTypeData::clear_codex_id_list() {
  codex_id_list_.Clear();
}
inline ::google::protobuf::uint32 CodexTypeData::codex_id_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CodexTypeData.codex_id_list)
  return codex_id_list_.Get(index);
}
inline void CodexTypeData::set_codex_id_list(int index, ::google::protobuf::uint32 value) {
  codex_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.CodexTypeData.codex_id_list)
}
inline void CodexTypeData::add_codex_id_list(::google::protobuf::uint32 value) {
  codex_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.CodexTypeData.codex_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CodexTypeData::codex_id_list() const {
  // @@protoc_insertion_point(field_list:proto.CodexTypeData.codex_id_list)
  return codex_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CodexTypeData::mutable_codex_id_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CodexTypeData.codex_id_list)
  return &codex_id_list_;
}

// map<uint32, uint32> weapon_max_promote_level_map = 4;
inline int CodexTypeData::weapon_max_promote_level_map_size() const {
  return weapon_max_promote_level_map_.size();
}
inline void CodexTypeData::clear_weapon_max_promote_level_map() {
  weapon_max_promote_level_map_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
CodexTypeData::weapon_max_promote_level_map() const {
  // @@protoc_insertion_point(field_map:proto.CodexTypeData.weapon_max_promote_level_map)
  return weapon_max_promote_level_map_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
CodexTypeData::mutable_weapon_max_promote_level_map() {
  // @@protoc_insertion_point(field_mutable_map:proto.CodexTypeData.weapon_max_promote_level_map)
  return weapon_max_promote_level_map_.MutableMap();
}

// .proto.CodexType type = 13;
inline void CodexTypeData::clear_type() {
  type_ = 0;
}
inline ::proto::CodexType CodexTypeData::type() const {
  // @@protoc_insertion_point(field_get:proto.CodexTypeData.type)
  return static_cast< ::proto::CodexType >(type_);
}
inline void CodexTypeData::set_type(::proto::CodexType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:proto.CodexTypeData.type)
}

// repeated bool have_viewed_list = 5;
inline int CodexTypeData::have_viewed_list_size() const {
  return have_viewed_list_.size();
}
inline void CodexTypeData::clear_have_viewed_list() {
  have_viewed_list_.Clear();
}
inline bool CodexTypeData::have_viewed_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CodexTypeData.have_viewed_list)
  return have_viewed_list_.Get(index);
}
inline void CodexTypeData::set_have_viewed_list(int index, bool value) {
  have_viewed_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.CodexTypeData.have_viewed_list)
}
inline void CodexTypeData::add_have_viewed_list(bool value) {
  have_viewed_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.CodexTypeData.have_viewed_list)
}
inline const ::google::protobuf::RepeatedField< bool >&
CodexTypeData::have_viewed_list() const {
  // @@protoc_insertion_point(field_list:proto.CodexTypeData.have_viewed_list)
  return have_viewed_list_;
}
inline ::google::protobuf::RepeatedField< bool >*
CodexTypeData::mutable_have_viewed_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CodexTypeData.have_viewed_list)
  return &have_viewed_list_;
}

// -------------------------------------------------------------------

// CodexDataFullNotify

// uint32 last_read_pushtips_codex_id = 4;
inline void CodexDataFullNotify::clear_last_read_pushtips_codex_id() {
  last_read_pushtips_codex_id_ = 0u;
}
inline ::google::protobuf::uint32 CodexDataFullNotify::last_read_pushtips_codex_id() const {
  // @@protoc_insertion_point(field_get:proto.CodexDataFullNotify.last_read_pushtips_codex_id)
  return last_read_pushtips_codex_id_;
}
inline void CodexDataFullNotify::set_last_read_pushtips_codex_id(::google::protobuf::uint32 value) {
  
  last_read_pushtips_codex_id_ = value;
  // @@protoc_insertion_point(field_set:proto.CodexDataFullNotify.last_read_pushtips_codex_id)
}

// repeated uint32 recent_viewed_pushtips_list = 2;
inline int CodexDataFullNotify::recent_viewed_pushtips_list_size() const {
  return recent_viewed_pushtips_list_.size();
}
inline void CodexDataFullNotify::clear_recent_viewed_pushtips_list() {
  recent_viewed_pushtips_list_.Clear();
}
inline ::google::protobuf::uint32 CodexDataFullNotify::recent_viewed_pushtips_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CodexDataFullNotify.recent_viewed_pushtips_list)
  return recent_viewed_pushtips_list_.Get(index);
}
inline void CodexDataFullNotify::set_recent_viewed_pushtips_list(int index, ::google::protobuf::uint32 value) {
  recent_viewed_pushtips_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.CodexDataFullNotify.recent_viewed_pushtips_list)
}
inline void CodexDataFullNotify::add_recent_viewed_pushtips_list(::google::protobuf::uint32 value) {
  recent_viewed_pushtips_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.CodexDataFullNotify.recent_viewed_pushtips_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CodexDataFullNotify::recent_viewed_pushtips_list() const {
  // @@protoc_insertion_point(field_list:proto.CodexDataFullNotify.recent_viewed_pushtips_list)
  return recent_viewed_pushtips_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CodexDataFullNotify::mutable_recent_viewed_pushtips_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CodexDataFullNotify.recent_viewed_pushtips_list)
  return &recent_viewed_pushtips_list_;
}

// uint32 last_read_pushtips_type_id = 3;
inline void CodexDataFullNotify::clear_last_read_pushtips_type_id() {
  last_read_pushtips_type_id_ = 0u;
}
inline ::google::protobuf::uint32 CodexDataFullNotify::last_read_pushtips_type_id() const {
  // @@protoc_insertion_point(field_get:proto.CodexDataFullNotify.last_read_pushtips_type_id)
  return last_read_pushtips_type_id_;
}
inline void CodexDataFullNotify::set_last_read_pushtips_type_id(::google::protobuf::uint32 value) {
  
  last_read_pushtips_type_id_ = value;
  // @@protoc_insertion_point(field_set:proto.CodexDataFullNotify.last_read_pushtips_type_id)
}

// repeated .proto.CodexTypeData type_data_list = 6;
inline int CodexDataFullNotify::type_data_list_size() const {
  return type_data_list_.size();
}
inline void CodexDataFullNotify::clear_type_data_list() {
  type_data_list_.Clear();
}
inline const ::proto::CodexTypeData& CodexDataFullNotify::type_data_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.CodexDataFullNotify.type_data_list)
  return type_data_list_.Get(index);
}
inline ::proto::CodexTypeData* CodexDataFullNotify::mutable_type_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.CodexDataFullNotify.type_data_list)
  return type_data_list_.Mutable(index);
}
inline ::proto::CodexTypeData* CodexDataFullNotify::add_type_data_list() {
  // @@protoc_insertion_point(field_add:proto.CodexDataFullNotify.type_data_list)
  return type_data_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >*
CodexDataFullNotify::mutable_type_data_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.CodexDataFullNotify.type_data_list)
  return &type_data_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >&
CodexDataFullNotify::type_data_list() const {
  // @@protoc_insertion_point(field_list:proto.CodexDataFullNotify.type_data_list)
  return type_data_list_;
}

// -------------------------------------------------------------------

// CodexDataUpdateNotify

// uint32 id = 8;
inline void CodexDataUpdateNotify::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 CodexDataUpdateNotify::id() const {
  // @@protoc_insertion_point(field_get:proto.CodexDataUpdateNotify.id)
  return id_;
}
inline void CodexDataUpdateNotify::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:proto.CodexDataUpdateNotify.id)
}

// uint32 weapon_max_promote_level = 15;
inline void CodexDataUpdateNotify::clear_weapon_max_promote_level() {
  weapon_max_promote_level_ = 0u;
}
inline ::google::protobuf::uint32 CodexDataUpdateNotify::weapon_max_promote_level() const {
  // @@protoc_insertion_point(field_get:proto.CodexDataUpdateNotify.weapon_max_promote_level)
  return weapon_max_promote_level_;
}
inline void CodexDataUpdateNotify::set_weapon_max_promote_level(::google::protobuf::uint32 value) {
  
  weapon_max_promote_level_ = value;
  // @@protoc_insertion_point(field_set:proto.CodexDataUpdateNotify.weapon_max_promote_level)
}

// .proto.CodexType type = 11;
inline void CodexDataUpdateNotify::clear_type() {
  type_ = 0;
}
inline ::proto::CodexType CodexDataUpdateNotify::type() const {
  // @@protoc_insertion_point(field_get:proto.CodexDataUpdateNotify.type)
  return static_cast< ::proto::CodexType >(type_);
}
inline void CodexDataUpdateNotify::set_type(::proto::CodexType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:proto.CodexDataUpdateNotify.type)
}

// -------------------------------------------------------------------

// QueryCodexMonsterBeKilledNumReq

// repeated uint32 codex_id_list = 14;
inline int QueryCodexMonsterBeKilledNumReq::codex_id_list_size() const {
  return codex_id_list_.size();
}
inline void QueryCodexMonsterBeKilledNumReq::clear_codex_id_list() {
  codex_id_list_.Clear();
}
inline ::google::protobuf::uint32 QueryCodexMonsterBeKilledNumReq::codex_id_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.QueryCodexMonsterBeKilledNumReq.codex_id_list)
  return codex_id_list_.Get(index);
}
inline void QueryCodexMonsterBeKilledNumReq::set_codex_id_list(int index, ::google::protobuf::uint32 value) {
  codex_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.QueryCodexMonsterBeKilledNumReq.codex_id_list)
}
inline void QueryCodexMonsterBeKilledNumReq::add_codex_id_list(::google::protobuf::uint32 value) {
  codex_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.QueryCodexMonsterBeKilledNumReq.codex_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
QueryCodexMonsterBeKilledNumReq::codex_id_list() const {
  // @@protoc_insertion_point(field_list:proto.QueryCodexMonsterBeKilledNumReq.codex_id_list)
  return codex_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
QueryCodexMonsterBeKilledNumReq::mutable_codex_id_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.QueryCodexMonsterBeKilledNumReq.codex_id_list)
  return &codex_id_list_;
}

// -------------------------------------------------------------------

// QueryCodexMonsterBeKilledNumRsp

// repeated uint32 codex_id_list = 4;
inline int QueryCodexMonsterBeKilledNumRsp::codex_id_list_size() const {
  return codex_id_list_.size();
}
inline void QueryCodexMonsterBeKilledNumRsp::clear_codex_id_list() {
  codex_id_list_.Clear();
}
inline ::google::protobuf::uint32 QueryCodexMonsterBeKilledNumRsp::codex_id_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.QueryCodexMonsterBeKilledNumRsp.codex_id_list)
  return codex_id_list_.Get(index);
}
inline void QueryCodexMonsterBeKilledNumRsp::set_codex_id_list(int index, ::google::protobuf::uint32 value) {
  codex_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.QueryCodexMonsterBeKilledNumRsp.codex_id_list)
}
inline void QueryCodexMonsterBeKilledNumRsp::add_codex_id_list(::google::protobuf::uint32 value) {
  codex_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.QueryCodexMonsterBeKilledNumRsp.codex_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
QueryCodexMonsterBeKilledNumRsp::codex_id_list() const {
  // @@protoc_insertion_point(field_list:proto.QueryCodexMonsterBeKilledNumRsp.codex_id_list)
  return codex_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
QueryCodexMonsterBeKilledNumRsp::mutable_codex_id_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.QueryCodexMonsterBeKilledNumRsp.codex_id_list)
  return &codex_id_list_;
}

// repeated uint32 be_captured_num_list = 6;
inline int QueryCodexMonsterBeKilledNumRsp::be_captured_num_list_size() const {
  return be_captured_num_list_.size();
}
inline void QueryCodexMonsterBeKilledNumRsp::clear_be_captured_num_list() {
  be_captured_num_list_.Clear();
}
inline ::google::protobuf::uint32 QueryCodexMonsterBeKilledNumRsp::be_captured_num_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.QueryCodexMonsterBeKilledNumRsp.be_captured_num_list)
  return be_captured_num_list_.Get(index);
}
inline void QueryCodexMonsterBeKilledNumRsp::set_be_captured_num_list(int index, ::google::protobuf::uint32 value) {
  be_captured_num_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.QueryCodexMonsterBeKilledNumRsp.be_captured_num_list)
}
inline void QueryCodexMonsterBeKilledNumRsp::add_be_captured_num_list(::google::protobuf::uint32 value) {
  be_captured_num_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.QueryCodexMonsterBeKilledNumRsp.be_captured_num_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
QueryCodexMonsterBeKilledNumRsp::be_captured_num_list() const {
  // @@protoc_insertion_point(field_list:proto.QueryCodexMonsterBeKilledNumRsp.be_captured_num_list)
  return be_captured_num_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
QueryCodexMonsterBeKilledNumRsp::mutable_be_captured_num_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.QueryCodexMonsterBeKilledNumRsp.be_captured_num_list)
  return &be_captured_num_list_;
}

// repeated uint32 be_killed_num_list = 12;
inline int QueryCodexMonsterBeKilledNumRsp::be_killed_num_list_size() const {
  return be_killed_num_list_.size();
}
inline void QueryCodexMonsterBeKilledNumRsp::clear_be_killed_num_list() {
  be_killed_num_list_.Clear();
}
inline ::google::protobuf::uint32 QueryCodexMonsterBeKilledNumRsp::be_killed_num_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.QueryCodexMonsterBeKilledNumRsp.be_killed_num_list)
  return be_killed_num_list_.Get(index);
}
inline void QueryCodexMonsterBeKilledNumRsp::set_be_killed_num_list(int index, ::google::protobuf::uint32 value) {
  be_killed_num_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.QueryCodexMonsterBeKilledNumRsp.be_killed_num_list)
}
inline void QueryCodexMonsterBeKilledNumRsp::add_be_killed_num_list(::google::protobuf::uint32 value) {
  be_killed_num_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.QueryCodexMonsterBeKilledNumRsp.be_killed_num_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
QueryCodexMonsterBeKilledNumRsp::be_killed_num_list() const {
  // @@protoc_insertion_point(field_list:proto.QueryCodexMonsterBeKilledNumRsp.be_killed_num_list)
  return be_killed_num_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
QueryCodexMonsterBeKilledNumRsp::mutable_be_killed_num_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.QueryCodexMonsterBeKilledNumRsp.be_killed_num_list)
  return &be_killed_num_list_;
}

// int32 retcode = 5;
inline void QueryCodexMonsterBeKilledNumRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 QueryCodexMonsterBeKilledNumRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.QueryCodexMonsterBeKilledNumRsp.retcode)
  return retcode_;
}
inline void QueryCodexMonsterBeKilledNumRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.QueryCodexMonsterBeKilledNumRsp.retcode)
}

// -------------------------------------------------------------------

// ViewCodexReq

// repeated .proto.CodexTypeData type_data_list = 10;
inline int ViewCodexReq::type_data_list_size() const {
  return type_data_list_.size();
}
inline void ViewCodexReq::clear_type_data_list() {
  type_data_list_.Clear();
}
inline const ::proto::CodexTypeData& ViewCodexReq::type_data_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ViewCodexReq.type_data_list)
  return type_data_list_.Get(index);
}
inline ::proto::CodexTypeData* ViewCodexReq::mutable_type_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.ViewCodexReq.type_data_list)
  return type_data_list_.Mutable(index);
}
inline ::proto::CodexTypeData* ViewCodexReq::add_type_data_list() {
  // @@protoc_insertion_point(field_add:proto.ViewCodexReq.type_data_list)
  return type_data_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >*
ViewCodexReq::mutable_type_data_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ViewCodexReq.type_data_list)
  return &type_data_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >&
ViewCodexReq::type_data_list() const {
  // @@protoc_insertion_point(field_list:proto.ViewCodexReq.type_data_list)
  return type_data_list_;
}

// -------------------------------------------------------------------

// ViewCodexRsp

// int32 retcode = 12;
inline void ViewCodexRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 ViewCodexRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.ViewCodexRsp.retcode)
  return retcode_;
}
inline void ViewCodexRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.ViewCodexRsp.retcode)
}

// repeated uint32 push_tips_reward_list = 10;
inline int ViewCodexRsp::push_tips_reward_list_size() const {
  return push_tips_reward_list_.size();
}
inline void ViewCodexRsp::clear_push_tips_reward_list() {
  push_tips_reward_list_.Clear();
}
inline ::google::protobuf::uint32 ViewCodexRsp::push_tips_reward_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ViewCodexRsp.push_tips_reward_list)
  return push_tips_reward_list_.Get(index);
}
inline void ViewCodexRsp::set_push_tips_reward_list(int index, ::google::protobuf::uint32 value) {
  push_tips_reward_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.ViewCodexRsp.push_tips_reward_list)
}
inline void ViewCodexRsp::add_push_tips_reward_list(::google::protobuf::uint32 value) {
  push_tips_reward_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.ViewCodexRsp.push_tips_reward_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ViewCodexRsp::push_tips_reward_list() const {
  // @@protoc_insertion_point(field_list:proto.ViewCodexRsp.push_tips_reward_list)
  return push_tips_reward_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ViewCodexRsp::mutable_push_tips_reward_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ViewCodexRsp.push_tips_reward_list)
  return &push_tips_reward_list_;
}

// repeated uint32 recent_viewed_pushtips_list = 3;
inline int ViewCodexRsp::recent_viewed_pushtips_list_size() const {
  return recent_viewed_pushtips_list_.size();
}
inline void ViewCodexRsp::clear_recent_viewed_pushtips_list() {
  recent_viewed_pushtips_list_.Clear();
}
inline ::google::protobuf::uint32 ViewCodexRsp::recent_viewed_pushtips_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ViewCodexRsp.recent_viewed_pushtips_list)
  return recent_viewed_pushtips_list_.Get(index);
}
inline void ViewCodexRsp::set_recent_viewed_pushtips_list(int index, ::google::protobuf::uint32 value) {
  recent_viewed_pushtips_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.ViewCodexRsp.recent_viewed_pushtips_list)
}
inline void ViewCodexRsp::add_recent_viewed_pushtips_list(::google::protobuf::uint32 value) {
  recent_viewed_pushtips_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.ViewCodexRsp.recent_viewed_pushtips_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ViewCodexRsp::recent_viewed_pushtips_list() const {
  // @@protoc_insertion_point(field_list:proto.ViewCodexRsp.recent_viewed_pushtips_list)
  return recent_viewed_pushtips_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ViewCodexRsp::mutable_recent_viewed_pushtips_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ViewCodexRsp.recent_viewed_pushtips_list)
  return &recent_viewed_pushtips_list_;
}

// repeated .proto.CodexTypeData type_data_list = 9;
inline int ViewCodexRsp::type_data_list_size() const {
  return type_data_list_.size();
}
inline void ViewCodexRsp::clear_type_data_list() {
  type_data_list_.Clear();
}
inline const ::proto::CodexTypeData& ViewCodexRsp::type_data_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ViewCodexRsp.type_data_list)
  return type_data_list_.Get(index);
}
inline ::proto::CodexTypeData* ViewCodexRsp::mutable_type_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.ViewCodexRsp.type_data_list)
  return type_data_list_.Mutable(index);
}
inline ::proto::CodexTypeData* ViewCodexRsp::add_type_data_list() {
  // @@protoc_insertion_point(field_add:proto.ViewCodexRsp.type_data_list)
  return type_data_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >*
ViewCodexRsp::mutable_type_data_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ViewCodexRsp.type_data_list)
  return &type_data_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::CodexTypeData >&
ViewCodexRsp::type_data_list() const {
  // @@protoc_insertion_point(field_list:proto.ViewCodexRsp.type_data_list)
  return type_data_list_;
}

// repeated uint32 push_tips_read_list = 15;
inline int ViewCodexRsp::push_tips_read_list_size() const {
  return push_tips_read_list_.size();
}
inline void ViewCodexRsp::clear_push_tips_read_list() {
  push_tips_read_list_.Clear();
}
inline ::google::protobuf::uint32 ViewCodexRsp::push_tips_read_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.ViewCodexRsp.push_tips_read_list)
  return push_tips_read_list_.Get(index);
}
inline void ViewCodexRsp::set_push_tips_read_list(int index, ::google::protobuf::uint32 value) {
  push_tips_read_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.ViewCodexRsp.push_tips_read_list)
}
inline void ViewCodexRsp::add_push_tips_read_list(::google::protobuf::uint32 value) {
  push_tips_read_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.ViewCodexRsp.push_tips_read_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ViewCodexRsp::push_tips_read_list() const {
  // @@protoc_insertion_point(field_list:proto.ViewCodexRsp.push_tips_read_list)
  return push_tips_read_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ViewCodexRsp::mutable_push_tips_read_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.ViewCodexRsp.push_tips_read_list)
  return &push_tips_read_list_;
}

// -------------------------------------------------------------------

// SetCodexPushtipsReadReq

// uint32 type_id = 2;
inline void SetCodexPushtipsReadReq::clear_type_id() {
  type_id_ = 0u;
}
inline ::google::protobuf::uint32 SetCodexPushtipsReadReq::type_id() const {
  // @@protoc_insertion_point(field_get:proto.SetCodexPushtipsReadReq.type_id)
  return type_id_;
}
inline void SetCodexPushtipsReadReq::set_type_id(::google::protobuf::uint32 value) {
  
  type_id_ = value;
  // @@protoc_insertion_point(field_set:proto.SetCodexPushtipsReadReq.type_id)
}

// uint32 codex_id = 14;
inline void SetCodexPushtipsReadReq::clear_codex_id() {
  codex_id_ = 0u;
}
inline ::google::protobuf::uint32 SetCodexPushtipsReadReq::codex_id() const {
  // @@protoc_insertion_point(field_get:proto.SetCodexPushtipsReadReq.codex_id)
  return codex_id_;
}
inline void SetCodexPushtipsReadReq::set_codex_id(::google::protobuf::uint32 value) {
  
  codex_id_ = value;
  // @@protoc_insertion_point(field_set:proto.SetCodexPushtipsReadReq.codex_id)
}

// -------------------------------------------------------------------

// SetCodexPushtipsReadRsp

// int32 retcode = 10;
inline void SetCodexPushtipsReadRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 SetCodexPushtipsReadRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.SetCodexPushtipsReadRsp.retcode)
  return retcode_;
}
inline void SetCodexPushtipsReadRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.SetCodexPushtipsReadRsp.retcode)
}

// uint32 type_id = 5;
inline void SetCodexPushtipsReadRsp::clear_type_id() {
  type_id_ = 0u;
}
inline ::google::protobuf::uint32 SetCodexPushtipsReadRsp::type_id() const {
  // @@protoc_insertion_point(field_get:proto.SetCodexPushtipsReadRsp.type_id)
  return type_id_;
}
inline void SetCodexPushtipsReadRsp::set_type_id(::google::protobuf::uint32 value) {
  
  type_id_ = value;
  // @@protoc_insertion_point(field_set:proto.SetCodexPushtipsReadRsp.type_id)
}

// uint32 codex_id = 14;
inline void SetCodexPushtipsReadRsp::clear_codex_id() {
  codex_id_ = 0u;
}
inline ::google::protobuf::uint32 SetCodexPushtipsReadRsp::codex_id() const {
  // @@protoc_insertion_point(field_get:proto.SetCodexPushtipsReadRsp.codex_id)
  return codex_id_;
}
inline void SetCodexPushtipsReadRsp::set_codex_id(::google::protobuf::uint32 value) {
  
  codex_id_ = value;
  // @@protoc_insertion_point(field_set:proto.SetCodexPushtipsReadRsp.codex_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::CodexDataFullNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::CodexDataFullNotify_CmdId>() {
  return ::proto::CodexDataFullNotify_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::CodexDataUpdateNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::CodexDataUpdateNotify_CmdId>() {
  return ::proto::CodexDataUpdateNotify_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::QueryCodexMonsterBeKilledNumReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::QueryCodexMonsterBeKilledNumReq_CmdId>() {
  return ::proto::QueryCodexMonsterBeKilledNumReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::QueryCodexMonsterBeKilledNumRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::QueryCodexMonsterBeKilledNumRsp_CmdId>() {
  return ::proto::QueryCodexMonsterBeKilledNumRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::ViewCodexReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::ViewCodexReq_CmdId>() {
  return ::proto::ViewCodexReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::ViewCodexRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::ViewCodexRsp_CmdId>() {
  return ::proto::ViewCodexRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::SetCodexPushtipsReadReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::SetCodexPushtipsReadReq_CmdId>() {
  return ::proto::SetCodexPushtipsReadReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::SetCodexPushtipsReadRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::SetCodexPushtipsReadRsp_CmdId>() {
  return ::proto::SetCodexPushtipsReadRsp_CmdId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5fcodex_2eproto__INCLUDED
