// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_miracle_ring.proto

#ifndef PROTOBUF_cmd_2fcmd_5fmiracle_5fring_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5fmiracle_5fring_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
#include "cmd/cmd_gadget.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class MiracleRingDataNotify;
class MiracleRingDataNotifyDefaultTypeInternal;
extern MiracleRingDataNotifyDefaultTypeInternal _MiracleRingDataNotify_default_instance_;
class MiracleRingDeliverItemReq;
class MiracleRingDeliverItemReqDefaultTypeInternal;
extern MiracleRingDeliverItemReqDefaultTypeInternal _MiracleRingDeliverItemReq_default_instance_;
class MiracleRingDeliverItemRsp;
class MiracleRingDeliverItemRspDefaultTypeInternal;
extern MiracleRingDeliverItemRspDefaultTypeInternal _MiracleRingDeliverItemRsp_default_instance_;
class MiracleRingDestroyNotify;
class MiracleRingDestroyNotifyDefaultTypeInternal;
extern MiracleRingDestroyNotifyDefaultTypeInternal _MiracleRingDestroyNotify_default_instance_;
class MiracleRingDropResultNotify;
class MiracleRingDropResultNotifyDefaultTypeInternal;
extern MiracleRingDropResultNotifyDefaultTypeInternal _MiracleRingDropResultNotify_default_instance_;
class MiracleRingTakeRewardReq;
class MiracleRingTakeRewardReqDefaultTypeInternal;
extern MiracleRingTakeRewardReqDefaultTypeInternal _MiracleRingTakeRewardReq_default_instance_;
class MiracleRingTakeRewardRsp;
class MiracleRingTakeRewardRspDefaultTypeInternal;
extern MiracleRingTakeRewardRspDefaultTypeInternal _MiracleRingTakeRewardRsp_default_instance_;
class UseMiracleRingReq;
class UseMiracleRingReqDefaultTypeInternal;
extern UseMiracleRingReqDefaultTypeInternal _UseMiracleRingReq_default_instance_;
class UseMiracleRingRsp;
class UseMiracleRingRspDefaultTypeInternal;
extern UseMiracleRingRspDefaultTypeInternal _UseMiracleRingRsp_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto

enum UseMiracleRingReq_CmdId {
  UseMiracleRingReq_CmdId_NONE = 0,
  UseMiracleRingReq_CmdId_CMD_ID = 5226,
  UseMiracleRingReq_CmdId_ENET_CHANNEL_ID = 0,
  UseMiracleRingReq_CmdId_ENET_IS_RELIABLE = 1,
  UseMiracleRingReq_CmdId_IS_ALLOW_CLIENT = 1,
  UseMiracleRingReq_CmdId_UseMiracleRingReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UseMiracleRingReq_CmdId_UseMiracleRingReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UseMiracleRingReq_CmdId_IsValid(int value);
const UseMiracleRingReq_CmdId UseMiracleRingReq_CmdId_CmdId_MIN = UseMiracleRingReq_CmdId_NONE;
const UseMiracleRingReq_CmdId UseMiracleRingReq_CmdId_CmdId_MAX = UseMiracleRingReq_CmdId_CMD_ID;
const int UseMiracleRingReq_CmdId_CmdId_ARRAYSIZE = UseMiracleRingReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* UseMiracleRingReq_CmdId_descriptor();
inline const ::std::string& UseMiracleRingReq_CmdId_Name(UseMiracleRingReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    UseMiracleRingReq_CmdId_descriptor(), value);
}
inline bool UseMiracleRingReq_CmdId_Parse(
    const ::std::string& name, UseMiracleRingReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UseMiracleRingReq_CmdId>(
    UseMiracleRingReq_CmdId_descriptor(), name, value);
}
enum UseMiracleRingReq_MiracleRingOpType {
  UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_NONE = 0,
  UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_PLACE = 1,
  UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_RETRACT = 2,
  UseMiracleRingReq_MiracleRingOpType_UseMiracleRingReq_MiracleRingOpType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UseMiracleRingReq_MiracleRingOpType_UseMiracleRingReq_MiracleRingOpType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UseMiracleRingReq_MiracleRingOpType_IsValid(int value);
const UseMiracleRingReq_MiracleRingOpType UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_MIN = UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_NONE;
const UseMiracleRingReq_MiracleRingOpType UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_MAX = UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_RETRACT;
const int UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_ARRAYSIZE = UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_MAX + 1;

const ::google::protobuf::EnumDescriptor* UseMiracleRingReq_MiracleRingOpType_descriptor();
inline const ::std::string& UseMiracleRingReq_MiracleRingOpType_Name(UseMiracleRingReq_MiracleRingOpType value) {
  return ::google::protobuf::internal::NameOfEnum(
    UseMiracleRingReq_MiracleRingOpType_descriptor(), value);
}
inline bool UseMiracleRingReq_MiracleRingOpType_Parse(
    const ::std::string& name, UseMiracleRingReq_MiracleRingOpType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UseMiracleRingReq_MiracleRingOpType>(
    UseMiracleRingReq_MiracleRingOpType_descriptor(), name, value);
}
enum UseMiracleRingRsp_CmdId {
  UseMiracleRingRsp_CmdId_NONE = 0,
  UseMiracleRingRsp_CmdId_CMD_ID = 5218,
  UseMiracleRingRsp_CmdId_ENET_CHANNEL_ID = 0,
  UseMiracleRingRsp_CmdId_ENET_IS_RELIABLE = 1,
  UseMiracleRingRsp_CmdId_UseMiracleRingRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UseMiracleRingRsp_CmdId_UseMiracleRingRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UseMiracleRingRsp_CmdId_IsValid(int value);
const UseMiracleRingRsp_CmdId UseMiracleRingRsp_CmdId_CmdId_MIN = UseMiracleRingRsp_CmdId_NONE;
const UseMiracleRingRsp_CmdId UseMiracleRingRsp_CmdId_CmdId_MAX = UseMiracleRingRsp_CmdId_CMD_ID;
const int UseMiracleRingRsp_CmdId_CmdId_ARRAYSIZE = UseMiracleRingRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* UseMiracleRingRsp_CmdId_descriptor();
inline const ::std::string& UseMiracleRingRsp_CmdId_Name(UseMiracleRingRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    UseMiracleRingRsp_CmdId_descriptor(), value);
}
inline bool UseMiracleRingRsp_CmdId_Parse(
    const ::std::string& name, UseMiracleRingRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UseMiracleRingRsp_CmdId>(
    UseMiracleRingRsp_CmdId_descriptor(), name, value);
}
enum MiracleRingDataNotify_CmdId {
  MiracleRingDataNotify_CmdId_NONE = 0,
  MiracleRingDataNotify_CmdId_CMD_ID = 5225,
  MiracleRingDataNotify_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingDataNotify_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingDataNotify_CmdId_MiracleRingDataNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingDataNotify_CmdId_MiracleRingDataNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingDataNotify_CmdId_IsValid(int value);
const MiracleRingDataNotify_CmdId MiracleRingDataNotify_CmdId_CmdId_MIN = MiracleRingDataNotify_CmdId_NONE;
const MiracleRingDataNotify_CmdId MiracleRingDataNotify_CmdId_CmdId_MAX = MiracleRingDataNotify_CmdId_CMD_ID;
const int MiracleRingDataNotify_CmdId_CmdId_ARRAYSIZE = MiracleRingDataNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingDataNotify_CmdId_descriptor();
inline const ::std::string& MiracleRingDataNotify_CmdId_Name(MiracleRingDataNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingDataNotify_CmdId_descriptor(), value);
}
inline bool MiracleRingDataNotify_CmdId_Parse(
    const ::std::string& name, MiracleRingDataNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingDataNotify_CmdId>(
    MiracleRingDataNotify_CmdId_descriptor(), name, value);
}
enum MiracleRingTakeRewardReq_CmdId {
  MiracleRingTakeRewardReq_CmdId_NONE = 0,
  MiracleRingTakeRewardReq_CmdId_CMD_ID = 5207,
  MiracleRingTakeRewardReq_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingTakeRewardReq_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingTakeRewardReq_CmdId_IS_ALLOW_CLIENT = 1,
  MiracleRingTakeRewardReq_CmdId_MiracleRingTakeRewardReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingTakeRewardReq_CmdId_MiracleRingTakeRewardReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingTakeRewardReq_CmdId_IsValid(int value);
const MiracleRingTakeRewardReq_CmdId MiracleRingTakeRewardReq_CmdId_CmdId_MIN = MiracleRingTakeRewardReq_CmdId_NONE;
const MiracleRingTakeRewardReq_CmdId MiracleRingTakeRewardReq_CmdId_CmdId_MAX = MiracleRingTakeRewardReq_CmdId_CMD_ID;
const int MiracleRingTakeRewardReq_CmdId_CmdId_ARRAYSIZE = MiracleRingTakeRewardReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingTakeRewardReq_CmdId_descriptor();
inline const ::std::string& MiracleRingTakeRewardReq_CmdId_Name(MiracleRingTakeRewardReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingTakeRewardReq_CmdId_descriptor(), value);
}
inline bool MiracleRingTakeRewardReq_CmdId_Parse(
    const ::std::string& name, MiracleRingTakeRewardReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingTakeRewardReq_CmdId>(
    MiracleRingTakeRewardReq_CmdId_descriptor(), name, value);
}
enum MiracleRingTakeRewardRsp_CmdId {
  MiracleRingTakeRewardRsp_CmdId_NONE = 0,
  MiracleRingTakeRewardRsp_CmdId_CMD_ID = 5202,
  MiracleRingTakeRewardRsp_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingTakeRewardRsp_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingTakeRewardRsp_CmdId_MiracleRingTakeRewardRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingTakeRewardRsp_CmdId_MiracleRingTakeRewardRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingTakeRewardRsp_CmdId_IsValid(int value);
const MiracleRingTakeRewardRsp_CmdId MiracleRingTakeRewardRsp_CmdId_CmdId_MIN = MiracleRingTakeRewardRsp_CmdId_NONE;
const MiracleRingTakeRewardRsp_CmdId MiracleRingTakeRewardRsp_CmdId_CmdId_MAX = MiracleRingTakeRewardRsp_CmdId_CMD_ID;
const int MiracleRingTakeRewardRsp_CmdId_CmdId_ARRAYSIZE = MiracleRingTakeRewardRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingTakeRewardRsp_CmdId_descriptor();
inline const ::std::string& MiracleRingTakeRewardRsp_CmdId_Name(MiracleRingTakeRewardRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingTakeRewardRsp_CmdId_descriptor(), value);
}
inline bool MiracleRingTakeRewardRsp_CmdId_Parse(
    const ::std::string& name, MiracleRingTakeRewardRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingTakeRewardRsp_CmdId>(
    MiracleRingTakeRewardRsp_CmdId_descriptor(), name, value);
}
enum MiracleRingDropResultNotify_CmdId {
  MiracleRingDropResultNotify_CmdId_NONE = 0,
  MiracleRingDropResultNotify_CmdId_CMD_ID = 5231,
  MiracleRingDropResultNotify_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingDropResultNotify_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingDropResultNotify_CmdId_MiracleRingDropResultNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingDropResultNotify_CmdId_MiracleRingDropResultNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingDropResultNotify_CmdId_IsValid(int value);
const MiracleRingDropResultNotify_CmdId MiracleRingDropResultNotify_CmdId_CmdId_MIN = MiracleRingDropResultNotify_CmdId_NONE;
const MiracleRingDropResultNotify_CmdId MiracleRingDropResultNotify_CmdId_CmdId_MAX = MiracleRingDropResultNotify_CmdId_CMD_ID;
const int MiracleRingDropResultNotify_CmdId_CmdId_ARRAYSIZE = MiracleRingDropResultNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingDropResultNotify_CmdId_descriptor();
inline const ::std::string& MiracleRingDropResultNotify_CmdId_Name(MiracleRingDropResultNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingDropResultNotify_CmdId_descriptor(), value);
}
inline bool MiracleRingDropResultNotify_CmdId_Parse(
    const ::std::string& name, MiracleRingDropResultNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingDropResultNotify_CmdId>(
    MiracleRingDropResultNotify_CmdId_descriptor(), name, value);
}
enum MiracleRingDeliverItemReq_CmdId {
  MiracleRingDeliverItemReq_CmdId_NONE = 0,
  MiracleRingDeliverItemReq_CmdId_CMD_ID = 5229,
  MiracleRingDeliverItemReq_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingDeliverItemReq_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingDeliverItemReq_CmdId_IS_ALLOW_CLIENT = 1,
  MiracleRingDeliverItemReq_CmdId_MiracleRingDeliverItemReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingDeliverItemReq_CmdId_MiracleRingDeliverItemReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingDeliverItemReq_CmdId_IsValid(int value);
const MiracleRingDeliverItemReq_CmdId MiracleRingDeliverItemReq_CmdId_CmdId_MIN = MiracleRingDeliverItemReq_CmdId_NONE;
const MiracleRingDeliverItemReq_CmdId MiracleRingDeliverItemReq_CmdId_CmdId_MAX = MiracleRingDeliverItemReq_CmdId_CMD_ID;
const int MiracleRingDeliverItemReq_CmdId_CmdId_ARRAYSIZE = MiracleRingDeliverItemReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingDeliverItemReq_CmdId_descriptor();
inline const ::std::string& MiracleRingDeliverItemReq_CmdId_Name(MiracleRingDeliverItemReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingDeliverItemReq_CmdId_descriptor(), value);
}
inline bool MiracleRingDeliverItemReq_CmdId_Parse(
    const ::std::string& name, MiracleRingDeliverItemReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingDeliverItemReq_CmdId>(
    MiracleRingDeliverItemReq_CmdId_descriptor(), name, value);
}
enum MiracleRingDeliverItemRsp_CmdId {
  MiracleRingDeliverItemRsp_CmdId_NONE = 0,
  MiracleRingDeliverItemRsp_CmdId_CMD_ID = 5222,
  MiracleRingDeliverItemRsp_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingDeliverItemRsp_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingDeliverItemRsp_CmdId_MiracleRingDeliverItemRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingDeliverItemRsp_CmdId_MiracleRingDeliverItemRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingDeliverItemRsp_CmdId_IsValid(int value);
const MiracleRingDeliverItemRsp_CmdId MiracleRingDeliverItemRsp_CmdId_CmdId_MIN = MiracleRingDeliverItemRsp_CmdId_NONE;
const MiracleRingDeliverItemRsp_CmdId MiracleRingDeliverItemRsp_CmdId_CmdId_MAX = MiracleRingDeliverItemRsp_CmdId_CMD_ID;
const int MiracleRingDeliverItemRsp_CmdId_CmdId_ARRAYSIZE = MiracleRingDeliverItemRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingDeliverItemRsp_CmdId_descriptor();
inline const ::std::string& MiracleRingDeliverItemRsp_CmdId_Name(MiracleRingDeliverItemRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingDeliverItemRsp_CmdId_descriptor(), value);
}
inline bool MiracleRingDeliverItemRsp_CmdId_Parse(
    const ::std::string& name, MiracleRingDeliverItemRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingDeliverItemRsp_CmdId>(
    MiracleRingDeliverItemRsp_CmdId_descriptor(), name, value);
}
enum MiracleRingDestroyNotify_CmdId {
  MiracleRingDestroyNotify_CmdId_NONE = 0,
  MiracleRingDestroyNotify_CmdId_CMD_ID = 5244,
  MiracleRingDestroyNotify_CmdId_ENET_CHANNEL_ID = 0,
  MiracleRingDestroyNotify_CmdId_ENET_IS_RELIABLE = 1,
  MiracleRingDestroyNotify_CmdId_MiracleRingDestroyNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MiracleRingDestroyNotify_CmdId_MiracleRingDestroyNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MiracleRingDestroyNotify_CmdId_IsValid(int value);
const MiracleRingDestroyNotify_CmdId MiracleRingDestroyNotify_CmdId_CmdId_MIN = MiracleRingDestroyNotify_CmdId_NONE;
const MiracleRingDestroyNotify_CmdId MiracleRingDestroyNotify_CmdId_CmdId_MAX = MiracleRingDestroyNotify_CmdId_CMD_ID;
const int MiracleRingDestroyNotify_CmdId_CmdId_ARRAYSIZE = MiracleRingDestroyNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MiracleRingDestroyNotify_CmdId_descriptor();
inline const ::std::string& MiracleRingDestroyNotify_CmdId_Name(MiracleRingDestroyNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MiracleRingDestroyNotify_CmdId_descriptor(), value);
}
inline bool MiracleRingDestroyNotify_CmdId_Parse(
    const ::std::string& name, MiracleRingDestroyNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MiracleRingDestroyNotify_CmdId>(
    MiracleRingDestroyNotify_CmdId_descriptor(), name, value);
}
// ===================================================================

class UseMiracleRingReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.UseMiracleRingReq) */ {
 public:
  UseMiracleRingReq();
  virtual ~UseMiracleRingReq();

  UseMiracleRingReq(const UseMiracleRingReq& from);

  inline UseMiracleRingReq& operator=(const UseMiracleRingReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UseMiracleRingReq(UseMiracleRingReq&& from) noexcept
    : UseMiracleRingReq() {
    *this = ::std::move(from);
  }

  inline UseMiracleRingReq& operator=(UseMiracleRingReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UseMiracleRingReq& default_instance();

  static inline const UseMiracleRingReq* internal_default_instance() {
    return reinterpret_cast<const UseMiracleRingReq*>(
               &_UseMiracleRingReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UseMiracleRingReq* other);
  friend void swap(UseMiracleRingReq& a, UseMiracleRingReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UseMiracleRingReq* New() const PROTOBUF_FINAL { return New(NULL); }

  UseMiracleRingReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UseMiracleRingReq& from);
  void MergeFrom(const UseMiracleRingReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UseMiracleRingReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef UseMiracleRingReq_CmdId CmdId;
  static const CmdId NONE =
    UseMiracleRingReq_CmdId_NONE;
  static const CmdId CMD_ID =
    UseMiracleRingReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    UseMiracleRingReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    UseMiracleRingReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    UseMiracleRingReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return UseMiracleRingReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    UseMiracleRingReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    UseMiracleRingReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    UseMiracleRingReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return UseMiracleRingReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return UseMiracleRingReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return UseMiracleRingReq_CmdId_Parse(name, value);
  }

  typedef UseMiracleRingReq_MiracleRingOpType MiracleRingOpType;
  static const MiracleRingOpType MIRACLE_RING_OP_NONE =
    UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_NONE;
  static const MiracleRingOpType MIRACLE_RING_OP_PLACE =
    UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_PLACE;
  static const MiracleRingOpType MIRACLE_RING_OP_RETRACT =
    UseMiracleRingReq_MiracleRingOpType_MIRACLE_RING_OP_RETRACT;
  static inline bool MiracleRingOpType_IsValid(int value) {
    return UseMiracleRingReq_MiracleRingOpType_IsValid(value);
  }
  static const MiracleRingOpType MiracleRingOpType_MIN =
    UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_MIN;
  static const MiracleRingOpType MiracleRingOpType_MAX =
    UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_MAX;
  static const int MiracleRingOpType_ARRAYSIZE =
    UseMiracleRingReq_MiracleRingOpType_MiracleRingOpType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MiracleRingOpType_descriptor() {
    return UseMiracleRingReq_MiracleRingOpType_descriptor();
  }
  static inline const ::std::string& MiracleRingOpType_Name(MiracleRingOpType value) {
    return UseMiracleRingReq_MiracleRingOpType_Name(value);
  }
  static inline bool MiracleRingOpType_Parse(const ::std::string& name,
      MiracleRingOpType* value) {
    return UseMiracleRingReq_MiracleRingOpType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.Vector rot = 7;
  bool has_rot() const;
  void clear_rot();
  static const int kRotFieldNumber = 7;
  const ::proto::Vector& rot() const;
  ::proto::Vector* mutable_rot();
  ::proto::Vector* release_rot();
  void set_allocated_rot(::proto::Vector* rot);

  // .proto.Vector pos = 8;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 8;
  const ::proto::Vector& pos() const;
  ::proto::Vector* mutable_pos();
  ::proto::Vector* release_pos();
  void set_allocated_pos(::proto::Vector* pos);

  // uint32 miracle_ring_op_type = 13;
  void clear_miracle_ring_op_type();
  static const int kMiracleRingOpTypeFieldNumber = 13;
  ::google::protobuf::uint32 miracle_ring_op_type() const;
  void set_miracle_ring_op_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.UseMiracleRingReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::Vector* rot_;
  ::proto::Vector* pos_;
  ::google::protobuf::uint32 miracle_ring_op_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UseMiracleRingRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.UseMiracleRingRsp) */ {
 public:
  UseMiracleRingRsp();
  virtual ~UseMiracleRingRsp();

  UseMiracleRingRsp(const UseMiracleRingRsp& from);

  inline UseMiracleRingRsp& operator=(const UseMiracleRingRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UseMiracleRingRsp(UseMiracleRingRsp&& from) noexcept
    : UseMiracleRingRsp() {
    *this = ::std::move(from);
  }

  inline UseMiracleRingRsp& operator=(UseMiracleRingRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UseMiracleRingRsp& default_instance();

  static inline const UseMiracleRingRsp* internal_default_instance() {
    return reinterpret_cast<const UseMiracleRingRsp*>(
               &_UseMiracleRingRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(UseMiracleRingRsp* other);
  friend void swap(UseMiracleRingRsp& a, UseMiracleRingRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UseMiracleRingRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  UseMiracleRingRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UseMiracleRingRsp& from);
  void MergeFrom(const UseMiracleRingRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UseMiracleRingRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef UseMiracleRingRsp_CmdId CmdId;
  static const CmdId NONE =
    UseMiracleRingRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    UseMiracleRingRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    UseMiracleRingRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    UseMiracleRingRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return UseMiracleRingRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    UseMiracleRingRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    UseMiracleRingRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    UseMiracleRingRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return UseMiracleRingRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return UseMiracleRingRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return UseMiracleRingRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 miracle_ring_op_type = 7;
  void clear_miracle_ring_op_type();
  static const int kMiracleRingOpTypeFieldNumber = 7;
  ::google::protobuf::uint32 miracle_ring_op_type() const;
  void set_miracle_ring_op_type(::google::protobuf::uint32 value);

  // int32 retcode = 11;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 11;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.UseMiracleRingRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 miracle_ring_op_type_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingDataNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingDataNotify) */ {
 public:
  MiracleRingDataNotify();
  virtual ~MiracleRingDataNotify();

  MiracleRingDataNotify(const MiracleRingDataNotify& from);

  inline MiracleRingDataNotify& operator=(const MiracleRingDataNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingDataNotify(MiracleRingDataNotify&& from) noexcept
    : MiracleRingDataNotify() {
    *this = ::std::move(from);
  }

  inline MiracleRingDataNotify& operator=(MiracleRingDataNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingDataNotify& default_instance();

  static inline const MiracleRingDataNotify* internal_default_instance() {
    return reinterpret_cast<const MiracleRingDataNotify*>(
               &_MiracleRingDataNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(MiracleRingDataNotify* other);
  friend void swap(MiracleRingDataNotify& a, MiracleRingDataNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingDataNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingDataNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingDataNotify& from);
  void MergeFrom(const MiracleRingDataNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingDataNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingDataNotify_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingDataNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingDataNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingDataNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingDataNotify_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingDataNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingDataNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingDataNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingDataNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingDataNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingDataNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingDataNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 last_take_reward_time = 14;
  void clear_last_take_reward_time();
  static const int kLastTakeRewardTimeFieldNumber = 14;
  ::google::protobuf::uint32 last_take_reward_time() const;
  void set_last_take_reward_time(::google::protobuf::uint32 value);

  // uint32 miracle_ring_cd = 7;
  void clear_miracle_ring_cd();
  static const int kMiracleRingCdFieldNumber = 7;
  ::google::protobuf::uint32 miracle_ring_cd() const;
  void set_miracle_ring_cd(::google::protobuf::uint32 value);

  // bool is_gadget_created = 8;
  void clear_is_gadget_created();
  static const int kIsGadgetCreatedFieldNumber = 8;
  bool is_gadget_created() const;
  void set_is_gadget_created(bool value);

  // uint32 last_deliver_item_time = 10;
  void clear_last_deliver_item_time();
  static const int kLastDeliverItemTimeFieldNumber = 10;
  ::google::protobuf::uint32 last_deliver_item_time() const;
  void set_last_deliver_item_time(::google::protobuf::uint32 value);

  // uint32 gadget_entity_id = 12;
  void clear_gadget_entity_id();
  static const int kGadgetEntityIdFieldNumber = 12;
  ::google::protobuf::uint32 gadget_entity_id() const;
  void set_gadget_entity_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingDataNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 last_take_reward_time_;
  ::google::protobuf::uint32 miracle_ring_cd_;
  bool is_gadget_created_;
  ::google::protobuf::uint32 last_deliver_item_time_;
  ::google::protobuf::uint32 gadget_entity_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingTakeRewardReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingTakeRewardReq) */ {
 public:
  MiracleRingTakeRewardReq();
  virtual ~MiracleRingTakeRewardReq();

  MiracleRingTakeRewardReq(const MiracleRingTakeRewardReq& from);

  inline MiracleRingTakeRewardReq& operator=(const MiracleRingTakeRewardReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingTakeRewardReq(MiracleRingTakeRewardReq&& from) noexcept
    : MiracleRingTakeRewardReq() {
    *this = ::std::move(from);
  }

  inline MiracleRingTakeRewardReq& operator=(MiracleRingTakeRewardReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingTakeRewardReq& default_instance();

  static inline const MiracleRingTakeRewardReq* internal_default_instance() {
    return reinterpret_cast<const MiracleRingTakeRewardReq*>(
               &_MiracleRingTakeRewardReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(MiracleRingTakeRewardReq* other);
  friend void swap(MiracleRingTakeRewardReq& a, MiracleRingTakeRewardReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingTakeRewardReq* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingTakeRewardReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingTakeRewardReq& from);
  void MergeFrom(const MiracleRingTakeRewardReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingTakeRewardReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingTakeRewardReq_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingTakeRewardReq_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingTakeRewardReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingTakeRewardReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingTakeRewardReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    MiracleRingTakeRewardReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingTakeRewardReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingTakeRewardReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingTakeRewardReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingTakeRewardReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingTakeRewardReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingTakeRewardReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingTakeRewardReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 gadget_entity_id = 7;
  void clear_gadget_entity_id();
  static const int kGadgetEntityIdFieldNumber = 7;
  ::google::protobuf::uint32 gadget_entity_id() const;
  void set_gadget_entity_id(::google::protobuf::uint32 value);

  // uint32 gadget_id = 11;
  void clear_gadget_id();
  static const int kGadgetIdFieldNumber = 11;
  ::google::protobuf::uint32 gadget_id() const;
  void set_gadget_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingTakeRewardReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 gadget_entity_id_;
  ::google::protobuf::uint32 gadget_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingTakeRewardRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingTakeRewardRsp) */ {
 public:
  MiracleRingTakeRewardRsp();
  virtual ~MiracleRingTakeRewardRsp();

  MiracleRingTakeRewardRsp(const MiracleRingTakeRewardRsp& from);

  inline MiracleRingTakeRewardRsp& operator=(const MiracleRingTakeRewardRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingTakeRewardRsp(MiracleRingTakeRewardRsp&& from) noexcept
    : MiracleRingTakeRewardRsp() {
    *this = ::std::move(from);
  }

  inline MiracleRingTakeRewardRsp& operator=(MiracleRingTakeRewardRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingTakeRewardRsp& default_instance();

  static inline const MiracleRingTakeRewardRsp* internal_default_instance() {
    return reinterpret_cast<const MiracleRingTakeRewardRsp*>(
               &_MiracleRingTakeRewardRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(MiracleRingTakeRewardRsp* other);
  friend void swap(MiracleRingTakeRewardRsp& a, MiracleRingTakeRewardRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingTakeRewardRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingTakeRewardRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingTakeRewardRsp& from);
  void MergeFrom(const MiracleRingTakeRewardRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingTakeRewardRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingTakeRewardRsp_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingTakeRewardRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingTakeRewardRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingTakeRewardRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingTakeRewardRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingTakeRewardRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingTakeRewardRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingTakeRewardRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingTakeRewardRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingTakeRewardRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingTakeRewardRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingTakeRewardRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 retcode = 14;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 14;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingTakeRewardRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingDropResultNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingDropResultNotify) */ {
 public:
  MiracleRingDropResultNotify();
  virtual ~MiracleRingDropResultNotify();

  MiracleRingDropResultNotify(const MiracleRingDropResultNotify& from);

  inline MiracleRingDropResultNotify& operator=(const MiracleRingDropResultNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingDropResultNotify(MiracleRingDropResultNotify&& from) noexcept
    : MiracleRingDropResultNotify() {
    *this = ::std::move(from);
  }

  inline MiracleRingDropResultNotify& operator=(MiracleRingDropResultNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingDropResultNotify& default_instance();

  static inline const MiracleRingDropResultNotify* internal_default_instance() {
    return reinterpret_cast<const MiracleRingDropResultNotify*>(
               &_MiracleRingDropResultNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(MiracleRingDropResultNotify* other);
  friend void swap(MiracleRingDropResultNotify& a, MiracleRingDropResultNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingDropResultNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingDropResultNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingDropResultNotify& from);
  void MergeFrom(const MiracleRingDropResultNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingDropResultNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingDropResultNotify_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingDropResultNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingDropResultNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingDropResultNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingDropResultNotify_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingDropResultNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingDropResultNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingDropResultNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingDropResultNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingDropResultNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingDropResultNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingDropResultNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 last_take_reward_time = 5;
  void clear_last_take_reward_time();
  static const int kLastTakeRewardTimeFieldNumber = 5;
  ::google::protobuf::int32 last_take_reward_time() const;
  void set_last_take_reward_time(::google::protobuf::int32 value);

  // int32 drop_result = 9;
  void clear_drop_result();
  static const int kDropResultFieldNumber = 9;
  ::google::protobuf::int32 drop_result() const;
  void set_drop_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingDropResultNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 last_take_reward_time_;
  ::google::protobuf::int32 drop_result_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingDeliverItemReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingDeliverItemReq) */ {
 public:
  MiracleRingDeliverItemReq();
  virtual ~MiracleRingDeliverItemReq();

  MiracleRingDeliverItemReq(const MiracleRingDeliverItemReq& from);

  inline MiracleRingDeliverItemReq& operator=(const MiracleRingDeliverItemReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingDeliverItemReq(MiracleRingDeliverItemReq&& from) noexcept
    : MiracleRingDeliverItemReq() {
    *this = ::std::move(from);
  }

  inline MiracleRingDeliverItemReq& operator=(MiracleRingDeliverItemReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingDeliverItemReq& default_instance();

  static inline const MiracleRingDeliverItemReq* internal_default_instance() {
    return reinterpret_cast<const MiracleRingDeliverItemReq*>(
               &_MiracleRingDeliverItemReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(MiracleRingDeliverItemReq* other);
  friend void swap(MiracleRingDeliverItemReq& a, MiracleRingDeliverItemReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingDeliverItemReq* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingDeliverItemReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingDeliverItemReq& from);
  void MergeFrom(const MiracleRingDeliverItemReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingDeliverItemReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingDeliverItemReq_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingDeliverItemReq_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingDeliverItemReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingDeliverItemReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingDeliverItemReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    MiracleRingDeliverItemReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingDeliverItemReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingDeliverItemReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingDeliverItemReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingDeliverItemReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingDeliverItemReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingDeliverItemReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingDeliverItemReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.ItemParam item_param_list = 1;
  int item_param_list_size() const;
  void clear_item_param_list();
  static const int kItemParamListFieldNumber = 1;
  const ::proto::ItemParam& item_param_list(int index) const;
  ::proto::ItemParam* mutable_item_param_list(int index);
  ::proto::ItemParam* add_item_param_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >*
      mutable_item_param_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >&
      item_param_list() const;

  // repeated uint64 food_weapon_guid_list = 4;
  int food_weapon_guid_list_size() const;
  void clear_food_weapon_guid_list();
  static const int kFoodWeaponGuidListFieldNumber = 4;
  ::google::protobuf::uint64 food_weapon_guid_list(int index) const;
  void set_food_weapon_guid_list(int index, ::google::protobuf::uint64 value);
  void add_food_weapon_guid_list(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      food_weapon_guid_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_food_weapon_guid_list();

  // uint32 gadget_id = 14;
  void clear_gadget_id();
  static const int kGadgetIdFieldNumber = 14;
  ::google::protobuf::uint32 gadget_id() const;
  void set_gadget_id(::google::protobuf::uint32 value);

  // uint32 gadget_entity_id = 5;
  void clear_gadget_entity_id();
  static const int kGadgetEntityIdFieldNumber = 5;
  ::google::protobuf::uint32 gadget_entity_id() const;
  void set_gadget_entity_id(::google::protobuf::uint32 value);

  // .proto.InterOpType op_type = 9;
  void clear_op_type();
  static const int kOpTypeFieldNumber = 9;
  ::proto::InterOpType op_type() const;
  void set_op_type(::proto::InterOpType value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingDeliverItemReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam > item_param_list_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > food_weapon_guid_list_;
  mutable int _food_weapon_guid_list_cached_byte_size_;
  ::google::protobuf::uint32 gadget_id_;
  ::google::protobuf::uint32 gadget_entity_id_;
  int op_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingDeliverItemRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingDeliverItemRsp) */ {
 public:
  MiracleRingDeliverItemRsp();
  virtual ~MiracleRingDeliverItemRsp();

  MiracleRingDeliverItemRsp(const MiracleRingDeliverItemRsp& from);

  inline MiracleRingDeliverItemRsp& operator=(const MiracleRingDeliverItemRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingDeliverItemRsp(MiracleRingDeliverItemRsp&& from) noexcept
    : MiracleRingDeliverItemRsp() {
    *this = ::std::move(from);
  }

  inline MiracleRingDeliverItemRsp& operator=(MiracleRingDeliverItemRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingDeliverItemRsp& default_instance();

  static inline const MiracleRingDeliverItemRsp* internal_default_instance() {
    return reinterpret_cast<const MiracleRingDeliverItemRsp*>(
               &_MiracleRingDeliverItemRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(MiracleRingDeliverItemRsp* other);
  friend void swap(MiracleRingDeliverItemRsp& a, MiracleRingDeliverItemRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingDeliverItemRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingDeliverItemRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingDeliverItemRsp& from);
  void MergeFrom(const MiracleRingDeliverItemRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingDeliverItemRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingDeliverItemRsp_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingDeliverItemRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingDeliverItemRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingDeliverItemRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingDeliverItemRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingDeliverItemRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingDeliverItemRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingDeliverItemRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingDeliverItemRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingDeliverItemRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingDeliverItemRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingDeliverItemRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.InteractType interact_type = 15;
  void clear_interact_type();
  static const int kInteractTypeFieldNumber = 15;
  ::proto::InteractType interact_type() const;
  void set_interact_type(::proto::InteractType value);

  // uint32 gadget_id = 4;
  void clear_gadget_id();
  static const int kGadgetIdFieldNumber = 4;
  ::google::protobuf::uint32 gadget_id() const;
  void set_gadget_id(::google::protobuf::uint32 value);

  // uint32 gadget_entity_id = 9;
  void clear_gadget_entity_id();
  static const int kGadgetEntityIdFieldNumber = 9;
  ::google::protobuf::uint32 gadget_entity_id() const;
  void set_gadget_entity_id(::google::protobuf::uint32 value);

  // int32 retcode = 11;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 11;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // .proto.InterOpType op_type = 14;
  void clear_op_type();
  static const int kOpTypeFieldNumber = 14;
  ::proto::InterOpType op_type() const;
  void set_op_type(::proto::InterOpType value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingDeliverItemRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int interact_type_;
  ::google::protobuf::uint32 gadget_id_;
  ::google::protobuf::uint32 gadget_entity_id_;
  ::google::protobuf::int32 retcode_;
  int op_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MiracleRingDestroyNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.MiracleRingDestroyNotify) */ {
 public:
  MiracleRingDestroyNotify();
  virtual ~MiracleRingDestroyNotify();

  MiracleRingDestroyNotify(const MiracleRingDestroyNotify& from);

  inline MiracleRingDestroyNotify& operator=(const MiracleRingDestroyNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MiracleRingDestroyNotify(MiracleRingDestroyNotify&& from) noexcept
    : MiracleRingDestroyNotify() {
    *this = ::std::move(from);
  }

  inline MiracleRingDestroyNotify& operator=(MiracleRingDestroyNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MiracleRingDestroyNotify& default_instance();

  static inline const MiracleRingDestroyNotify* internal_default_instance() {
    return reinterpret_cast<const MiracleRingDestroyNotify*>(
               &_MiracleRingDestroyNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(MiracleRingDestroyNotify* other);
  friend void swap(MiracleRingDestroyNotify& a, MiracleRingDestroyNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MiracleRingDestroyNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  MiracleRingDestroyNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MiracleRingDestroyNotify& from);
  void MergeFrom(const MiracleRingDestroyNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MiracleRingDestroyNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MiracleRingDestroyNotify_CmdId CmdId;
  static const CmdId NONE =
    MiracleRingDestroyNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    MiracleRingDestroyNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    MiracleRingDestroyNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    MiracleRingDestroyNotify_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return MiracleRingDestroyNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    MiracleRingDestroyNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    MiracleRingDestroyNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    MiracleRingDestroyNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return MiracleRingDestroyNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return MiracleRingDestroyNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return MiracleRingDestroyNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 entity_id = 7;
  void clear_entity_id();
  static const int kEntityIdFieldNumber = 7;
  ::google::protobuf::uint32 entity_id() const;
  void set_entity_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.MiracleRingDestroyNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 entity_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fmiracle_5fring_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UseMiracleRingReq

// uint32 miracle_ring_op_type = 13;
inline void UseMiracleRingReq::clear_miracle_ring_op_type() {
  miracle_ring_op_type_ = 0u;
}
inline ::google::protobuf::uint32 UseMiracleRingReq::miracle_ring_op_type() const {
  // @@protoc_insertion_point(field_get:proto.UseMiracleRingReq.miracle_ring_op_type)
  return miracle_ring_op_type_;
}
inline void UseMiracleRingReq::set_miracle_ring_op_type(::google::protobuf::uint32 value) {
  
  miracle_ring_op_type_ = value;
  // @@protoc_insertion_point(field_set:proto.UseMiracleRingReq.miracle_ring_op_type)
}

// .proto.Vector pos = 8;
inline bool UseMiracleRingReq::has_pos() const {
  return this != internal_default_instance() && pos_ != NULL;
}
inline void UseMiracleRingReq::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) delete pos_;
  pos_ = NULL;
}
inline const ::proto::Vector& UseMiracleRingReq::pos() const {
  const ::proto::Vector* p = pos_;
  // @@protoc_insertion_point(field_get:proto.UseMiracleRingReq.pos)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Vector*>(
      &::proto::_Vector_default_instance_);
}
inline ::proto::Vector* UseMiracleRingReq::mutable_pos() {
  
  if (pos_ == NULL) {
    pos_ = new ::proto::Vector;
  }
  // @@protoc_insertion_point(field_mutable:proto.UseMiracleRingReq.pos)
  return pos_;
}
inline ::proto::Vector* UseMiracleRingReq::release_pos() {
  // @@protoc_insertion_point(field_release:proto.UseMiracleRingReq.pos)
  
  ::proto::Vector* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void UseMiracleRingReq::set_allocated_pos(::proto::Vector* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.UseMiracleRingReq.pos)
}

// .proto.Vector rot = 7;
inline bool UseMiracleRingReq::has_rot() const {
  return this != internal_default_instance() && rot_ != NULL;
}
inline void UseMiracleRingReq::clear_rot() {
  if (GetArenaNoVirtual() == NULL && rot_ != NULL) delete rot_;
  rot_ = NULL;
}
inline const ::proto::Vector& UseMiracleRingReq::rot() const {
  const ::proto::Vector* p = rot_;
  // @@protoc_insertion_point(field_get:proto.UseMiracleRingReq.rot)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Vector*>(
      &::proto::_Vector_default_instance_);
}
inline ::proto::Vector* UseMiracleRingReq::mutable_rot() {
  
  if (rot_ == NULL) {
    rot_ = new ::proto::Vector;
  }
  // @@protoc_insertion_point(field_mutable:proto.UseMiracleRingReq.rot)
  return rot_;
}
inline ::proto::Vector* UseMiracleRingReq::release_rot() {
  // @@protoc_insertion_point(field_release:proto.UseMiracleRingReq.rot)
  
  ::proto::Vector* temp = rot_;
  rot_ = NULL;
  return temp;
}
inline void UseMiracleRingReq::set_allocated_rot(::proto::Vector* rot) {
  delete rot_;
  rot_ = rot;
  if (rot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto.UseMiracleRingReq.rot)
}

// -------------------------------------------------------------------

// UseMiracleRingRsp

// int32 retcode = 11;
inline void UseMiracleRingRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 UseMiracleRingRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.UseMiracleRingRsp.retcode)
  return retcode_;
}
inline void UseMiracleRingRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.UseMiracleRingRsp.retcode)
}

// uint32 miracle_ring_op_type = 7;
inline void UseMiracleRingRsp::clear_miracle_ring_op_type() {
  miracle_ring_op_type_ = 0u;
}
inline ::google::protobuf::uint32 UseMiracleRingRsp::miracle_ring_op_type() const {
  // @@protoc_insertion_point(field_get:proto.UseMiracleRingRsp.miracle_ring_op_type)
  return miracle_ring_op_type_;
}
inline void UseMiracleRingRsp::set_miracle_ring_op_type(::google::protobuf::uint32 value) {
  
  miracle_ring_op_type_ = value;
  // @@protoc_insertion_point(field_set:proto.UseMiracleRingRsp.miracle_ring_op_type)
}

// -------------------------------------------------------------------

// MiracleRingDataNotify

// bool is_gadget_created = 8;
inline void MiracleRingDataNotify::clear_is_gadget_created() {
  is_gadget_created_ = false;
}
inline bool MiracleRingDataNotify::is_gadget_created() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDataNotify.is_gadget_created)
  return is_gadget_created_;
}
inline void MiracleRingDataNotify::set_is_gadget_created(bool value) {
  
  is_gadget_created_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDataNotify.is_gadget_created)
}

// uint32 last_take_reward_time = 14;
inline void MiracleRingDataNotify::clear_last_take_reward_time() {
  last_take_reward_time_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDataNotify::last_take_reward_time() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDataNotify.last_take_reward_time)
  return last_take_reward_time_;
}
inline void MiracleRingDataNotify::set_last_take_reward_time(::google::protobuf::uint32 value) {
  
  last_take_reward_time_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDataNotify.last_take_reward_time)
}

// uint32 gadget_entity_id = 12;
inline void MiracleRingDataNotify::clear_gadget_entity_id() {
  gadget_entity_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDataNotify::gadget_entity_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDataNotify.gadget_entity_id)
  return gadget_entity_id_;
}
inline void MiracleRingDataNotify::set_gadget_entity_id(::google::protobuf::uint32 value) {
  
  gadget_entity_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDataNotify.gadget_entity_id)
}

// uint32 last_deliver_item_time = 10;
inline void MiracleRingDataNotify::clear_last_deliver_item_time() {
  last_deliver_item_time_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDataNotify::last_deliver_item_time() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDataNotify.last_deliver_item_time)
  return last_deliver_item_time_;
}
inline void MiracleRingDataNotify::set_last_deliver_item_time(::google::protobuf::uint32 value) {
  
  last_deliver_item_time_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDataNotify.last_deliver_item_time)
}

// uint32 miracle_ring_cd = 7;
inline void MiracleRingDataNotify::clear_miracle_ring_cd() {
  miracle_ring_cd_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDataNotify::miracle_ring_cd() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDataNotify.miracle_ring_cd)
  return miracle_ring_cd_;
}
inline void MiracleRingDataNotify::set_miracle_ring_cd(::google::protobuf::uint32 value) {
  
  miracle_ring_cd_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDataNotify.miracle_ring_cd)
}

// -------------------------------------------------------------------

// MiracleRingTakeRewardReq

// uint32 gadget_id = 11;
inline void MiracleRingTakeRewardReq::clear_gadget_id() {
  gadget_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingTakeRewardReq::gadget_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingTakeRewardReq.gadget_id)
  return gadget_id_;
}
inline void MiracleRingTakeRewardReq::set_gadget_id(::google::protobuf::uint32 value) {
  
  gadget_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingTakeRewardReq.gadget_id)
}

// uint32 gadget_entity_id = 7;
inline void MiracleRingTakeRewardReq::clear_gadget_entity_id() {
  gadget_entity_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingTakeRewardReq::gadget_entity_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingTakeRewardReq.gadget_entity_id)
  return gadget_entity_id_;
}
inline void MiracleRingTakeRewardReq::set_gadget_entity_id(::google::protobuf::uint32 value) {
  
  gadget_entity_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingTakeRewardReq.gadget_entity_id)
}

// -------------------------------------------------------------------

// MiracleRingTakeRewardRsp

// int32 retcode = 14;
inline void MiracleRingTakeRewardRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 MiracleRingTakeRewardRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingTakeRewardRsp.retcode)
  return retcode_;
}
inline void MiracleRingTakeRewardRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingTakeRewardRsp.retcode)
}

// -------------------------------------------------------------------

// MiracleRingDropResultNotify

// int32 last_take_reward_time = 5;
inline void MiracleRingDropResultNotify::clear_last_take_reward_time() {
  last_take_reward_time_ = 0;
}
inline ::google::protobuf::int32 MiracleRingDropResultNotify::last_take_reward_time() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDropResultNotify.last_take_reward_time)
  return last_take_reward_time_;
}
inline void MiracleRingDropResultNotify::set_last_take_reward_time(::google::protobuf::int32 value) {
  
  last_take_reward_time_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDropResultNotify.last_take_reward_time)
}

// int32 drop_result = 9;
inline void MiracleRingDropResultNotify::clear_drop_result() {
  drop_result_ = 0;
}
inline ::google::protobuf::int32 MiracleRingDropResultNotify::drop_result() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDropResultNotify.drop_result)
  return drop_result_;
}
inline void MiracleRingDropResultNotify::set_drop_result(::google::protobuf::int32 value) {
  
  drop_result_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDropResultNotify.drop_result)
}

// -------------------------------------------------------------------

// MiracleRingDeliverItemReq

// .proto.InterOpType op_type = 9;
inline void MiracleRingDeliverItemReq::clear_op_type() {
  op_type_ = 0;
}
inline ::proto::InterOpType MiracleRingDeliverItemReq::op_type() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemReq.op_type)
  return static_cast< ::proto::InterOpType >(op_type_);
}
inline void MiracleRingDeliverItemReq::set_op_type(::proto::InterOpType value) {
  
  op_type_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemReq.op_type)
}

// repeated .proto.ItemParam item_param_list = 1;
inline int MiracleRingDeliverItemReq::item_param_list_size() const {
  return item_param_list_.size();
}
inline void MiracleRingDeliverItemReq::clear_item_param_list() {
  item_param_list_.Clear();
}
inline const ::proto::ItemParam& MiracleRingDeliverItemReq::item_param_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemReq.item_param_list)
  return item_param_list_.Get(index);
}
inline ::proto::ItemParam* MiracleRingDeliverItemReq::mutable_item_param_list(int index) {
  // @@protoc_insertion_point(field_mutable:proto.MiracleRingDeliverItemReq.item_param_list)
  return item_param_list_.Mutable(index);
}
inline ::proto::ItemParam* MiracleRingDeliverItemReq::add_item_param_list() {
  // @@protoc_insertion_point(field_add:proto.MiracleRingDeliverItemReq.item_param_list)
  return item_param_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >*
MiracleRingDeliverItemReq::mutable_item_param_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.MiracleRingDeliverItemReq.item_param_list)
  return &item_param_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >&
MiracleRingDeliverItemReq::item_param_list() const {
  // @@protoc_insertion_point(field_list:proto.MiracleRingDeliverItemReq.item_param_list)
  return item_param_list_;
}

// repeated uint64 food_weapon_guid_list = 4;
inline int MiracleRingDeliverItemReq::food_weapon_guid_list_size() const {
  return food_weapon_guid_list_.size();
}
inline void MiracleRingDeliverItemReq::clear_food_weapon_guid_list() {
  food_weapon_guid_list_.Clear();
}
inline ::google::protobuf::uint64 MiracleRingDeliverItemReq::food_weapon_guid_list(int index) const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemReq.food_weapon_guid_list)
  return food_weapon_guid_list_.Get(index);
}
inline void MiracleRingDeliverItemReq::set_food_weapon_guid_list(int index, ::google::protobuf::uint64 value) {
  food_weapon_guid_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemReq.food_weapon_guid_list)
}
inline void MiracleRingDeliverItemReq::add_food_weapon_guid_list(::google::protobuf::uint64 value) {
  food_weapon_guid_list_.Add(value);
  // @@protoc_insertion_point(field_add:proto.MiracleRingDeliverItemReq.food_weapon_guid_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
MiracleRingDeliverItemReq::food_weapon_guid_list() const {
  // @@protoc_insertion_point(field_list:proto.MiracleRingDeliverItemReq.food_weapon_guid_list)
  return food_weapon_guid_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
MiracleRingDeliverItemReq::mutable_food_weapon_guid_list() {
  // @@protoc_insertion_point(field_mutable_list:proto.MiracleRingDeliverItemReq.food_weapon_guid_list)
  return &food_weapon_guid_list_;
}

// uint32 gadget_id = 14;
inline void MiracleRingDeliverItemReq::clear_gadget_id() {
  gadget_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDeliverItemReq::gadget_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemReq.gadget_id)
  return gadget_id_;
}
inline void MiracleRingDeliverItemReq::set_gadget_id(::google::protobuf::uint32 value) {
  
  gadget_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemReq.gadget_id)
}

// uint32 gadget_entity_id = 5;
inline void MiracleRingDeliverItemReq::clear_gadget_entity_id() {
  gadget_entity_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDeliverItemReq::gadget_entity_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemReq.gadget_entity_id)
  return gadget_entity_id_;
}
inline void MiracleRingDeliverItemReq::set_gadget_entity_id(::google::protobuf::uint32 value) {
  
  gadget_entity_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemReq.gadget_entity_id)
}

// -------------------------------------------------------------------

// MiracleRingDeliverItemRsp

// .proto.InteractType interact_type = 15;
inline void MiracleRingDeliverItemRsp::clear_interact_type() {
  interact_type_ = 0;
}
inline ::proto::InteractType MiracleRingDeliverItemRsp::interact_type() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemRsp.interact_type)
  return static_cast< ::proto::InteractType >(interact_type_);
}
inline void MiracleRingDeliverItemRsp::set_interact_type(::proto::InteractType value) {
  
  interact_type_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemRsp.interact_type)
}

// int32 retcode = 11;
inline void MiracleRingDeliverItemRsp::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 MiracleRingDeliverItemRsp::retcode() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemRsp.retcode)
  return retcode_;
}
inline void MiracleRingDeliverItemRsp::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemRsp.retcode)
}

// .proto.InterOpType op_type = 14;
inline void MiracleRingDeliverItemRsp::clear_op_type() {
  op_type_ = 0;
}
inline ::proto::InterOpType MiracleRingDeliverItemRsp::op_type() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemRsp.op_type)
  return static_cast< ::proto::InterOpType >(op_type_);
}
inline void MiracleRingDeliverItemRsp::set_op_type(::proto::InterOpType value) {
  
  op_type_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemRsp.op_type)
}

// uint32 gadget_id = 4;
inline void MiracleRingDeliverItemRsp::clear_gadget_id() {
  gadget_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDeliverItemRsp::gadget_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemRsp.gadget_id)
  return gadget_id_;
}
inline void MiracleRingDeliverItemRsp::set_gadget_id(::google::protobuf::uint32 value) {
  
  gadget_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemRsp.gadget_id)
}

// uint32 gadget_entity_id = 9;
inline void MiracleRingDeliverItemRsp::clear_gadget_entity_id() {
  gadget_entity_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDeliverItemRsp::gadget_entity_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDeliverItemRsp.gadget_entity_id)
  return gadget_entity_id_;
}
inline void MiracleRingDeliverItemRsp::set_gadget_entity_id(::google::protobuf::uint32 value) {
  
  gadget_entity_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDeliverItemRsp.gadget_entity_id)
}

// -------------------------------------------------------------------

// MiracleRingDestroyNotify

// uint32 entity_id = 7;
inline void MiracleRingDestroyNotify::clear_entity_id() {
  entity_id_ = 0u;
}
inline ::google::protobuf::uint32 MiracleRingDestroyNotify::entity_id() const {
  // @@protoc_insertion_point(field_get:proto.MiracleRingDestroyNotify.entity_id)
  return entity_id_;
}
inline void MiracleRingDestroyNotify::set_entity_id(::google::protobuf::uint32 value) {
  
  entity_id_ = value;
  // @@protoc_insertion_point(field_set:proto.MiracleRingDestroyNotify.entity_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::UseMiracleRingReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::UseMiracleRingReq_CmdId>() {
  return ::proto::UseMiracleRingReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::UseMiracleRingReq_MiracleRingOpType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::UseMiracleRingReq_MiracleRingOpType>() {
  return ::proto::UseMiracleRingReq_MiracleRingOpType_descriptor();
}
template <> struct is_proto_enum< ::proto::UseMiracleRingRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::UseMiracleRingRsp_CmdId>() {
  return ::proto::UseMiracleRingRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingDataNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingDataNotify_CmdId>() {
  return ::proto::MiracleRingDataNotify_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingTakeRewardReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingTakeRewardReq_CmdId>() {
  return ::proto::MiracleRingTakeRewardReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingTakeRewardRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingTakeRewardRsp_CmdId>() {
  return ::proto::MiracleRingTakeRewardRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingDropResultNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingDropResultNotify_CmdId>() {
  return ::proto::MiracleRingDropResultNotify_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingDeliverItemReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingDeliverItemReq_CmdId>() {
  return ::proto::MiracleRingDeliverItemReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingDeliverItemRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingDeliverItemRsp_CmdId>() {
  return ::proto::MiracleRingDeliverItemRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::MiracleRingDestroyNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::MiracleRingDestroyNotify_CmdId>() {
  return ::proto::MiracleRingDestroyNotify_CmdId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5fmiracle_5fring_2eproto__INCLUDED
